<?php

	$ud=$this->bodycontent;
	
	$session=(array)$this->mydetails;
	
?>
	<html>
	    <head>
	         <script type="text/javascript" src="http://js.freniz.com/jquery-latest.js"></script> 
	        <script type="text/javascript" src="http://js.freniz.com/ajax.js"></script> 
	        <link rel="stylesheet" href="http://css.freniz.com/default.css" type="text/css" media="screen" charset="utf-8" />
	          <script type="text/javascript" src="http://js.freniz.com/leaf.js"></script> 
	      <script src="http://js.freniz.com/jquery.timeago.js" type="text/javascript"></script>
	     <link rel="stylesheet" href="http://css.freniz.com/autosuggest_inquisitor.css" type="text/css" media="screen" charset="utf-8" />
	       <script type="text/javascript" src="http://js.freniz.com/bsn.AutoSuggest_c_2.0.js"></script>
        
         <script type="text/javascript">

	     $(document).ready(function(event){
	    	 $('.admire-new').click(function(){
	             
	    		 $c='<div style="width:500px; height:200px; margin-left:20px; margin-top:20px; "><form name="admiremess"onsubmit="createadmirestatus()"><div style="width:300px; height:100px; margin-top:10px; margin-left:60px; float:left;"><textarea placeholder="write an admire to this person"style="width:400px; height:100px"name="admr"></textarea></div><div style="width:300px; "><input id="leaf-vote" type="button"name="admire-cancel"value="cancel"onClick="document.getElementById(\'light\').style.display=\'none\';   document.getElementById(\'fade\').style.display=\'none\';"/><input id="leaf-vote" type="button"name="admire-send"value="send"onclick="createadmirestatus(\'<?php echo $ud['userid'] ?>\')"/></div></form></div>';

	    		     $('#light').html($c); 
	    		              $('#light').css({'display':'block'});
	    		              $('#fade').css({'display':'block'});
	    		             
	    		         });
	     });
	     </script>
	      <style>
#remove-items{
			border-radius: 10px;
-moz-border-radius: 10px;
-webkit-border-radius: 10px;
-moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
-webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
-ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);
		}
#remove-items ul{
		display:inline;
		width:70px;
            background-color:#eee;
		
	}
	#remove-items ul li{
		display:block;
		background-color:#FFF;
		padding:7px;
	
	background-color:#eee;
		
		
	}
	#remove-items ul li a{
		margin-top:-10px;
		text-decoration:none;
		color:black;
		position:absolute;
	font-size:12px;
		padding:2px;
	}
	#remove-items ul li a:hover{
		background-color:#A4A4A4;
		width:70px;
		display:block;
		color:#FFF;
		 -moz-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  -webkit-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);	
		padding:2px;
		
		
	}
	a{
		color:#444;
		text-decoration:none;
	}
	     </style>
	    </head>
	    <body>
   <img id="loading" src="images/prettyGallery/loading-gif-animation.gif" style="position:absolute; display: none; margin-left: 45%" height="32" width="32"></img>
    <div class="headerdiv">
<div id="freniz-logo" style="width:220px; float:left; height:60px; ">
    <a style="text-decoration:none; cursor: pointer; "href="#"><img src="http://images.freniz.com/freniz.png"/></a>
</div>
<div id="smile-mood-change" style="width:40px; float:left; height:60px; ">
<?php if(isset($session['userid']) && $session['type']!='none' && $session['type']!='leaf'){ ?>
   <div style="width:40px; margin-top: 10px; float:left; height:40px; "><img id="top-smiley" style="cursor: pointer;marin-top:10px" src="http://images.freniz.com/mood/32/<?php $smood=explode(',', $session['mood']); echo $smood[0];?>" width="40" height="40"/></div>
<?php } ?>
</div>
<div id="top-menu-items" style=" float:left; height:60px; ">
<div style="height:30px; margin-top: 15px; margin-left: 30px;  float:left; ">
    <?php if(isset($session['userid']) && $session['type']=='user'){ ?>
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/">Stream</a></li>
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/<?php echo $session['userid']; ?>">Bio</a></li>
	<li class="link-bord" id="top-underline"><a id="mes-a" href="http://www.freniz.com/messages">Message</a></li>
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/blog/<?php echo $session['userid']; ?>">Blog</a></li>
	
	<li class="link-bord">
		<a id="alert-a" href="#">Alert</a>
				<ul style=" margin-top: -5px;">
					<li><a id="noti-a" href="http://www.freniz.com/notification">Notifications</a></li>
					<li><a id="revi-a" href="http://www.freniz.com/review/reviews">Reviews</a></li>
				</ul>				
	</li>
	<li class="link-bord">
		<a href="#">Apps</a>	
		<ul style=" margin-top: -5px;">
					 <li ><a href="http://www.freniz.com/forum">Forum</a></li>
                    <li><a href="http://www.freniz.com/diary">Diary</a></li>
					<li><a href="http://www.freniz.com/slambook">Slam book</a></li>
				</ul>		
	</li>
	
</ul>
<?php }else{ ?>
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/<?php echo $session['userid']; ?>">Home</a></li>
<ul>

<?php } ?>
</div>

</div>
<div style=" width: 250px; margin-right: 10px; float:right; height:60px; ">
<?php if($session['userid']){ ?> 
<div id="accout-name-settings" style=" float:right; font-weight: bold; color: #fff; height:40px;">
   
 <nav>
           <ul>
		<li id="settings">
			<a id="acount-trigger-setting" href="javascript:void(0)" title="<?php echo $session['username']; ?>" class="active">
				<?php 
				$name = $session['username'];
                 if(strlen($name) > 24 )
                 {
                 echo substr($name, 0, 26).'...' ;
                                 }
               else {
                   echo $name;
               } ?> <span id="logspan">&#x25BC;</span>
			</a>
			<div id="acount-content-setting" >
                            <ul>
                                <label style="color:#999; font-size: 18px; font-weight: bold">Freniz Account</label>
                                <?php 
                                $val=$session['adminpages_details'];
                                unset($val[$session['userid']]);
                                foreach ($val as $value){
                                	?>
                            		<li title="<?php echo $value['username']; ?>" onclick="switchuser('<?php echo $value['userid'];?>')"  ><div style="border-bottom:solid 1px #ccc; padding:3px; height:16px"><label  style="color:#999; height:16px;float:left;font-weight: bold"><img style="width:16px; height:16px; float:left" src="http://images.freniz.com/32/32_<?php echo $value['propic_url'];?>"/><a title="<?php echo $value['username']; ?>" style="font-size:10px;padding-left:4px;"><?php $leafname = $value['username'];
                 if(strlen($leafname) > 15 )
                 {
                 echo substr($leafname, 0, 15).'...' ;
                                 }
               else {
                   echo $leafname; } ?></a></label></div></li>
                                 	<?php } 
                                 	if($session['type']!='none' && $session['type']!='leaf'){
                                 	?>
                                 	 <li ><a href="http://www.freniz.com/index/personalinfo?log_aug=finis">Account Settings</a></li>
                                 <li><a href="http://www.freniz.com/index/privacysettings">Privacy Setting</a> </li>
                                <?php }elseif($session['type']=='leaf'){ ?>
                                   <li><a href="http://www.freniz.com/leafedit/<?php echo $session['userid']; ?>#privacyinfo">Privacy Setting</a> </li>
                                <?php } ?>
                                 <li><a href="#">Help</a></li>
                                 <li><a href="http://www.freniz.com/index/logout">Take Out</a> </li>
                            </ul>
			</div>                     
		</li>
                
            </ul>
        </nav>

    
 
</div>
 <?php }else {?>
      <div style="width:250px; height: 40px; float:right">
             <a style=" padding:3px 10px; float:right" href="http://www.freniz.com/loginattempt" id="leaf-vote">Login</a>
          </div>
    <?php } ?>
 
<div id="search-option-items" style="width:200px; margin-top: -10px;margin-right:50px;  float:right; height:20px; ">
    <input class="search-box" id="searchusers"  type="text" placeholder="search" onfocusout="searchitemsout(this)" onfocus="searchitemsin(this)" style="width:250px; height:30px" ><span id="searchusers-load" style="margin-top:-24px; margin-left: 215px; color: #ffffff; display: none; position: absolute;"><img src="images/blackloading.gif" height="16" width="16"/></span></input>
    <span style="color:#ccc; cursor: pointer; font-size: 12px; float: right; margin-top: -24px; margin-right:-45px">&#x25BC;</span>
</div>
</div>


</div>             
	        <div style="width:1000px; margin-left: auto; margin-top:5px; margin-right: auto;">
	        <div id="maincontainer">
	        	
	           <!-- main div close --> 
	              
	            
	            <div id="displaycontainer" style="width:1000px;float: left;  ">
	          <?php if($ud['userid']!=$session['userid']){?>
	            <div style="width:250px;margin-top: 10px;  float: right; ">
	                           <span class="admire-new"  style="margin-top: 10px;" id="leaf-vote">Add Admire</span>
	               <div id="sponcer"style="width:250px;margin-top: 10px; height:100px; border:solid 1px;  float: right; ">
	               </div>             
	             </div> 
	          <?php }?>
	            <div style="width:700px;float: left; ">
	            
	            <label style="font-size: 24px; 	text-transform: uppercase; "><?php echo $ud['username'];?>'s Admiration</label>
	            
	            <!-- text feild -->
	            
	           <!-- text feild close --> 
	         <!-- blog start -->   
	         <script type="text/javascript">
				getadmire('<?php echo $ud['userid']; ?>');
	         </script>
	 <div id="admires" style="width: 700px; margin-top:5px; float: left;">
             </div>
             </div></div>
	            <!-- blog close -->
	            <div id="footer" style="width: 100%; height: 100px; float: left; ">
    
    
    
</div>
 
	            </div>
	           </div> 
	         
	         
<script type="text/javascript">

				
getcount();	
								
					function miniprofile(data,element){
							var position=$(element).offset();
							getminiprofile(data,position.top,position.left);
						}


					var options_xmlsearch = function(type,appendto){
					     if(!appendto)
					        appendto='body'; 
					     var options={
					                script:"http://www.freniz.com/search?type="+type+"&",
							varname:"key",
					                type:type,
					                appendto:appendto,
					                callback:function(suggestion,fld){
												window.location.href="http://www.freniz.com/"+suggestion.id;
					                       }
					                
					            };
					            return options;
						}
           var options_xmlsearch = new AutoSuggest('searchusers', options_xmlsearch('all'));
        
        
        
</script>
<div id="light" class="white_content"></div>
    <div id="fade" onClick="document.getElementById('light').style.display='none';  document.getElementById('fade').style.display='none'" class="black_overlay">
        </div>
		 <div id="musictab">

 <div class="foot-tab">
     <ul>
         <li><a href="#">About</a></li>
         <li><a href="http://www.freniz.com/search">Search</a></li>
         <li><a href="#">Terms</a></li>
         <li><a href="#">Privacy</a></li>
         <li><a href="#">Help</a></li>
         <li><a href="http://www.freniz.com/createleaf">Create a leaf</a></li>
          <li><a href="http://www.freniz.com/developers">Developers</a></li>
         <li><a href="http://www.freniz.com/hireus">Hire Us</a></li>
     </ul>
     
 </div> 
       
</div>
	    </body>  
	    
	    
	    
	    
	</html>
