    <html>
    <body>
    <h1>Example</h1>
    <?php if (count($this->paginator)): ?>
    <ul>
    <?php foreach ($this->paginator as $item): ?>
      <li><?php print_r($item); ?></li>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>
     
    <?php echo $this->paginationControl($this->paginator,
                                        'elastic',
                                        'temp/temp.phtml'); ?>
    </body>
    </html>