<?php

	$session=(array)$this->mydetails;
	$ud=$this->userDetails;
	
?>
	<html>
	    <head>
	         <script type="text/javascript" src="http://js.freniz.com/ajax.js"></script> 
	       
	        <script type="text/javascript" src="http://js.freniz.com/jquery-latest.js"></script> 
	        <link rel="stylesheet" href="http://css.freniz.com/default.css" type="text/css" media="screen" charset="utf-8" />
	      <script type='text/javascript' src="http://js.freniz.com/jquery.form.js"></script>
	             <script type="text/javascript" src="http://js.freniz.com/leaf.js"></script> 
	        <script src="http://js.freniz.com/jquery.timeago.js" type="text/javascript"></script>
	        <script type="text/javascript" src="http://js.freniz.com/bsn.AutoSuggest_c_2.0.js"></script>
<link rel="stylesheet" href="http://css.freniz.com/autosuggest_inquisitor.css" type="text/css" media="screen" charset="utf-8" />
 
	     <style>
#remove-items{
			border-radius: 10px;
-moz-border-radius: 10px;
-webkit-border-radius: 10px;
-moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
-webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
-ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);
		}
#remove-items ul{
		display:inline;
		width:100px;
            background-color:#eee;
	}
	#remove-items ul li{
		display:block;
		background-color:#FFF;
		padding:10px;
	background-color:#eee;
		
		
	}
	#remove-items ul li a{
		text-decoration:none;
		color:black;
		position:absolute;
		padding:2px;
	}
	#remove-items ul li a:hover{
		background-color:#A4A4A4;
		width:100px;
		display:block;
		color:#FFF;
		 -moz-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  -webkit-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);	
		padding:2px;
		
		
	}
	#user-pic{
            	     border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
             -moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        -webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
	        -ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);		
	}
  #stature-stream{
            	     border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
             -moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        -webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
	        -ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);
            background-color:#eee;
           
            }
.vote-bar {
                text-decoration: none;
                cursor: pointer;
                font-size: 14px; font-weight: bold;
                color: #000;
            }
           .vote-bar :hover{
                color: #fff;
            }
            .close {
                text-decoration: none;
                cursor: pointer;
                font-size: 8px; font-weight: bold;
                color: #000;
            }
            .close:hover{
                color: #aaa;
            }
navg ul {
		  margin-top:10px;
		  padding: 2px;
		  list-style: none;
		  position: relative;
		  float: left;
		  background: #eee;
		  border-bottom: 1px solid #fff;
		  -moz-border-radius: 3px;
		  -webkit-border-radius: 3px;
		  border-radius: 3px;    
		}
		
		navg li {
		  float: left;      
			   border-left:solid 1px; 
		}
     
      navg li:first-child  a{
		   
			border-left:solid 1px #eee; 
		}
		
		navg #acountmenu a {
		  display: inline-block;
		  /*display: inline;
		  *zoom: 1;  */
		  height: 25px;
		  line-height: 25px;
		  font-weight: bold;
		  padding: 0 8px;
		  text-decoration: none;
		  color: #444;
		  text-shadow: 0 1px 0 #fff; 
		}
		
		navg #acountmenu a {
		  -moz-border-radius: 0 3px 3px 0;
		  -webkit-border-radius: 0 3px 3px 0;
		  border-radius: 0 3px 3px 0;
		}
		
		
			navg #acountmenu-trigger {
		  -moz-border-radius: 3px 0 0 3px;
		  -webkit-border-radius: 3px 0 0 3px;
		  border-radius: 3px 0 0 3px;
		}
		
		navg #acountmenu a:hover {
		  background: #fff;
		}
		.active{
		  background: #fff;
		}

	     </style>
	    
	        <script type="text/javascript">
			$(document).ready(function(event){

	    	     $('#post-image').ajaxForm({
		    	     dataType:'json',
		    	     cache:false,
		    	     success:function(json){
			    	     alert(json);
			    	     }
	    	     });
				$('.hover').live('mouseover',function(){
					var data=$(this).attr('data');
					miniprofile(data,this);
					$(".hover-div").live('mouseover',function() {
					    $('.hover-div').css('display','block');
					  }).live('mouseout',function(){
						  $('.hover-div').css('display','none');
					  });
					}).live('mouseout',function(){
						 $('.hover-div').css('display','none');
					  });
				$('.mes-text').live('mouseover', function() {
				    $('.mes-text').toggle(function() {
				    	$('#mes-text').css('display','block');
				    	$('.mes-text').html('cancel');
				    },function(){
				    	$('#mes-text').css('display','none');
				    	$('.mes-text').html('send text');
				    });
				});
		$('#text-post-link').click(function(){
			$('#text-post').css('display','block');
			$('#video-post').css('display','none');
			$('#text-post-link').addClass('active');
			$('#video-post-link').removeClass('active');
			$('#image-post-link').removeClass('active');
			$('#image-post').css('display','none');
		
	});
		$('#video-post-link').click(function(){
			$('#video-post').css('display','block');
			$('#text-post').css('display','none');
			$('#video-post-link').addClass('active');
			$('#text-post-link').removeClass('active');
			$('#image-post-link').removeClass('active');
			$('#image-post').css('display','none');
		
	});
		$('#image-post-link').click(function(){
			$('#image-post').css('display','block');
			$('#video-post').css('display','none');
			$('#text-post').css('display','none');
			$('#image-post-link').addClass('active');
			$('#text-post-link').removeClass('active');
			$('#video-post-link').removeClass('active');
			
	});

		
});
			
			function miniprofile(data,element){
					var position=$(element).offset();
					getminiprofile(data,position.top,position.left);
				}	
			        
			</script>  
	    </head>
	    <body>
 <img id="loading" src="images/prettyGallery/loading-gif-animation.gif" style="position:absolute; display: none; margin-left: 45%" height="32" width="32"></img>
    <div class="headerdiv">
<div id="freniz-logo" style="width:220px; float:left; height:60px; ">
    <a style="text-decoration:none; cursor: pointer; "href="#"><img src="http://images.freniz.com/freniz.png"/></a>
</div>
<div id="smile-mood-change" style="width:40px; float:left; height:60px; ">
<?php if(isset($session['userid']) && $session['type']!='none' && $session['type']!='leaf'){ ?>
   <div style="width:40px; margin-top: 10px; float:left; height:40px; "><img id="top-smiley" style="cursor: pointer;marin-top:10px" src="http://images.freniz.com/mood/32/<?php $smood=explode(',', $session['mood']); echo $smood[0];?>" width="40" height="40"/></div>
<?php } ?>
</div>
<div id="top-menu-items" style=" float:left; height:60px; ">
<div style="height:30px; margin-top: 15px; margin-left: 30px;  float:left; ">
    <?php if(isset($session['userid']) && $session['type']=='user'){ ?>
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/">Stream</a></li>
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/<?php echo $session['userid']; ?>">Bio</a></li>
	<li class="link-bord" id="top-underline"><a id="mes-a" href="http://www.freniz.com/messages">Message</a></li>
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/blog/<?php echo $session['userid']; ?>">Blog</a></li>
	
	<li class="link-bord">
		<a id="alert-a" href="#">Alert</a>
				<ul style=" margin-top: -5px;">
					<li><a id="noti-a" href="http://www.freniz.com/notification">Notifications</a></li>
					<li><a id="revi-a" href="http://www.freniz.com/review/reviews">Reviews</a></li>
				</ul>				
	</li>
	<li class="link-bord">
		<a href="#">Apps</a>	
		<ul style=" margin-top: -5px;">
					 <li ><a href="http://www.freniz.com/forum">Forum</a></li>
                    <li><a href="http://www.freniz.com/diary">Diary</a></li>
					<li><a href="http://www.freniz.com/slambook">Slam book</a></li>
				</ul>		
	</li>
	
</ul>
<?php }else{ ?>
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/<?php echo $session['userid']; ?>">Home</a></li>
<ul>

<?php } ?>
</div>

</div>
<div style=" width: 250px; margin-right: 10px; float:right; height:60px; ">
<?php if($session['userid']){ ?> 
<div id="accout-name-settings" style=" float:right; font-weight: bold; color: #fff; height:40px;">
   
 <nav>
           <ul>
		<li id="settings">
			<a id="acount-trigger-setting" href="javascript:void(0)" title="<?php echo $session['username']; ?>" class="active">
				<?php 
				$name = $session['username'];
                 if(strlen($name) > 24 )
                 {
                 echo substr($name, 0, 26).'...' ;
                                 }
               else {
                   echo $name;
               } ?> <span id="logspan">&#x25BC;</span>
			</a>
			<div id="acount-content-setting" >
                            <ul>
                                <label style="color:#999; font-size: 18px; font-weight: bold">Freniz Account</label>
                                <?php 
                                $val=$session['adminpages_details'];
                                unset($val[$session['userid']]);
                                foreach ($val as $value){
                                	?>
                            		<li title="<?php echo $value['username']; ?>" onclick="switchuser('<?php echo $value['userid'];?>')"  ><div style="border-bottom:solid 1px #ccc; padding:3px; height:16px"><label  style="color:#999; height:16px;float:left;font-weight: bold"><img style="width:16px; height:16px; float:left" src="http://images.freniz.com/32/32_<?php echo $value['propic_url'];?>"/><a title="<?php echo $value['username']; ?>" style="font-size:10px;padding-left:4px;"><?php $leafname = $value['username'];
                 if(strlen($leafname) > 15 )
                 {
                 echo substr($leafname, 0, 15).'...' ;
                                 }
               else {
                   echo $leafname; } ?></a></label></div></li>
                                 	<?php } 
                                 	if($session['type']!='none' && $session['type']!='leaf'){
                                 	?>
                                 	 <li ><a href="http://www.freniz.com/index/personalinfo?log_aug=finis">Account Settings</a></li>
                                 <li><a href="http://www.freniz.com/index/privacysettings">Privacy Setting</a> </li>
                                <?php }elseif($session['type']=='leaf'){ ?>
                                   <li><a href="http://www.freniz.com/leafedit/<?php echo $session['userid']; ?>#privacyinfo">Privacy Setting</a> </li>
                                <?php } ?>
                                 <li><a href="#">Help</a></li>
                                 <li><a href="http://www.freniz.com/index/logout">Take Out</a> </li>
                            </ul>
			</div>                     
		</li>
                
            </ul>
        </nav>

    
 
</div>
 <?php }else {?>
      <div style="width:250px; height: 40px; float:right">
             <a style=" padding:3px 10px; float:right" href="http://www.freniz.com/loginattempt" id="leaf-vote">Login</a>
          </div>
    <?php } ?>
 
<div id="search-option-items" style="width:200px; margin-top: -10px;margin-right:50px;  float:right; height:20px; ">
    <input class="search-box" id="searchusers"  type="text" placeholder="search" onfocusout="searchitemsout(this)" onfocus="searchitemsin(this)" style="width:250px; height:30px" ><span id="searchusers-load" style="margin-top:-24px; margin-left: 215px; color: #ffffff; display: none; position: absolute;"><img src="images/blackloading.gif" height="16" width="16"/></span></input>
    <span style="color:#ccc; cursor: pointer; font-size: 12px; float: right; margin-top: -24px; margin-right:-45px">&#x25BC;</span>
</div>
</div>


</div>  
     <div  style="width:1000px; margin-top:5px;  margin-left: auto;  margin-right: auto;">
	        <div id="maincontainer">
	           
	           <!-- main div close --> 
	              
	            
	            <div  style="width:1000px;float: left;  ">
	         
	            <div style="width:700px;float: left; ">
	            
	            <label style="font-size: 24px; 	text-transform: uppercase; "><?php echo $ud['username'];?>'s scribbles</label>
	            
	            <!-- text feild -->
	            
				  <div style="width:600px; margin-left:15px; float:left">
				       
				       
				       <navg>
							<ul id="acountmenu" >
								
								<li style="border-left:solid 1px #eee"><a class="active" href="javascript:void(0)" id="text-post-link" >Text</a></li>
								<li ><a href="javascript:void(0)" id="video-post-link" >Video</a></li>
								<li ><a href="javascript:void(0)" id="image-post-link" >Photo</a></li>
							</ul>
						</navg>
						<?php if($session['userid']==$ud['userid']){?>
						<div style="float: right; margin-top:20px; width:120px;height:20px;"><label style="float: left; padding-right:5px">post</label><select id="post-pt"><option <?php if( $ud['privacy_post']=='friends') {echo 'selected="selected"';} ?> value="friends">Friends</option><option <?php if( $ud['privacy_post']=='fof') {echo 'selected="selected"';} ?> value="fof">FOF</option><option <?php if( $ud['privacy_post']=='public') {echo 'selected="selected"';} ?> value="public">Public</option><option <?php if( $ud['privacy_post']=='private') {echo 'selected="selected"';} ?> value="private">Private</option><option <?php if( $ud['privacy_post']=='specific') {echo 'selected="selected"';} ?> value="specific">Specific</option></select></div>
				
						<div style="float:right; margin-top:20px; height:20px; width:150px"><label style="float: left;padding-right:5px">comment</label><select id="comment-pt"><option <?php if( $ud['privacy_post']=='friends') {echo 'selected="selected"';} ?> value="friends">Friends</option><option <?php if( $ud['privacy_post']=='fof') {echo 'selected="selected"';} ?> value="fof">FOF</option><option <?php if( $ud['privacy_post']=='public') {echo 'selected="selected"';} ?> value="public">Public</option><option <?php if( $ud['privacy_post']=='private') {echo 'selected="selected"';} ?> value="private">Private</option><option <?php if( $ud['privacy_post']=='specific') {echo 'selected="selected"';} ?> value="specific">Specific</option></select></div>
				<?php }?>
				        <div id="video-post" style="width:700px; margin-top:-20px;display:none; float:left; padding:10px; border-bottom:solid 1px">
					      <input id="video-title" type="text" style="width: 300px; height:30px" placeholder="Title"/>
					            <input id="video-embeddcode" type="text" style="width: 300px; height:30px" placeholder="Embeddcode"/>
					      <span style="float:right; margin-top:10px;" onclick="postvideos('<?php echo $ud['userid']; ?>')"id="leaf-vote">Post</span>
					      </div>
					       <div id="text-post" style="width:700px; margin-top:-20px;  float:left; padding:10px;  border-bottom:solid 1px">
					      <input id="scribble-content" type="text" style="width: 600px; height:30px" placeholder="Enter text to post"/>
					      <span style="float:right; margin-top:10px;" id="leaf-vote"onclick="postscribbles('<?php echo $ud['userid'];?>','user')">Post</span>
					      </div>
					      <div id="image-post" style="width:700px; display:none;margin-top:-20px;  float:left; padding:10px;  border-bottom:solid 1px">
		                   <form name="post-image" action="http://www.freniz.com/uploadimage" method="post" id="post-image" enctype="multipart/form-data" >
		                  <input type="hidden" name="album" value="<?php echo $ud['chartpic'];?>" />
		                   <input name="text" id="image-content" type="text" style="width: 600px; height:30px" placeholder="Enter your story"/>
					      <input type="file" id="image_url" name="qqfile" value="Upload" size="40" />
		                      <input style="float:right; margin-top:10px;" type="submit" id="leaf-vote"value="Post"/>
		                   </form>
					      </div>
				       
				       
				</div>
	            
	           <!-- text feild close --> 
	         <!-- blog start -->   
	      
	        <script type="text/javascript">
	        getscribbles('<?php echo $ud['userid'];?>');
	        </script>
	       <div id="scribbles" style="width: 700px; margin-top:5px; float: left;">
            </div> 
	         </div>
	         
	          <div style="width:250px; float:right; height: 300px; ">
	          
	          
	            </div>
	            
	         
	         </div>
	            <!-- blog close -->
	            
	           <div id="footer" style="width: 100%; height: 100px; float: left; ">
    
    
    
</div>
 
	            
	            </div>
	           </div> 
	          
	          
	
	      <!-- <div style="border: solid 1px; width:100%; height:270px; background-image:url(http://images.freniz.com/banner.png)"></div>  --> 
	   
	   <div id="remove-items" style="width:130px; display:none; background-color:#eee;float:left; ">
<ul>
<li class="delete" ><a href="javascript:void(0)">delete</a></li>
<li><a href="javascript:void(0)">Settings</a></li>
<li><a  href="javascript:void(0)">Report</a></li>
</ul>
</div> 
 <script type="text/javascript">

				
getcount();	
								
					function miniprofile(data,element){
							var position=$(element).offset();
							getminiprofile(data,position.top,position.left);
						}


					var options_xmlsearch = function(type,appendto){
					     if(!appendto)
					        appendto='body'; 
					     var options={
					                script:"http://www.freniz.com/search?type="+type+"&",
							varname:"key",
					                type:type,
					                appendto:appendto,
					                callback:function(suggestion,fld){
												window.location.href="http://www.freniz.com/"+suggestion.id;
					                       }
					                
					            };
					            return options;
						}
           var options_xmlsearch = new AutoSuggest('searchusers', options_xmlsearch('all'));
        
        
        
</script>
	 <div id="musictab">

 <div class="foot-tab">
    <ul>
 <li><a href="#">About</a></li>
         <li><a href="http://www.freniz.com/search">Search</a></li>
         <li><a href="#">Terms</a></li>
         <li><a href="#">Privacy</a></li>
         <li><a href="#">Help</a></li>
         <li><a href="http://www.freniz.com/createleaf">Create a leaf</a></li>
          <li><a href="http://www.freniz.com/developers">Developers</a></li>
         <li><a href="http://www.freniz.com/hireus">Hire Us</a></li>
     </ul>
     
 </div> 
       
</div> 
 <div id="hover-data"></div> 
	    </body>  
	    
	    
	    
	    
	</html>
