<?php 
$session=(array)$this->mydetails;
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-type" content="text/html;charset=UTF-8" /> 
		<title>Freniz-crop</title>
		<script src="http://localhost/freniz_zend/public/js/jquery.js" type="text/javascript"></script>
		<script src="http://localhost/freniz_zend/public/js/jquery.Jcrop.js" type="text/javascript"></script>
		<link rel="stylesheet" href="http://localhost/freniz_zend/public/css/jquery.Jcrop.css" type="text/css" />
		<script src="http://localhost/freniz_zend/public/js/ajax.js" type="text/javascript" ></script>
			<link rel="stylesheet" href="http://localhost/freniz_zend/public/css/default.css" type="text/css" media="screen" charset="utf-8" />
<link rel="stylesheet" href="http://localhost/freniz_zend/public/css/theme.css" type="text/css" media="screen" charset="utf-8" />
	<style type="text/css">
#leaf-vote{
	            
	    	  cursor: pointer;
			  font-weight: bold;
			  padding: 3px 10px;
			  text-decoration: none;
			  color: #000;
			  text-shadow: 0 1px 0 #fff; 
			  -moz-border-radius: 6px;
			  -webkit-border-radius: 6px;
			  border-radius: 6px;
	                  background-color: rgb(146,213,0);
			  background-image: -webkit-gradient(linear, left top, left bottom, from(rgb(146,213,0)), to(rgb(146,213,0)));
			  background-image: -webkit-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: -moz-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: -ms-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: -o-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
	                   -webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	-ms-box-sizing: border-box;
	-o-box-sizing: border-box;
	box-sizing: border-box;
	-webkit-box-shadow: 0 1px 0 rgba(255, 255, 255, 0.07),0 1px 0 rgba(255, 255, 255, 0.07) inset;
	-moz-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
	-ms-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
	-o-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
	box-shadow: 0 1px 0 rgba(255, 255, 255, 0.07),0 1px 0 rgba(255, 255, 255, 0.07) inset;
	        
	        }
	        #leaf-vote:hover{
	            color:#fff;
	            
	        }

</style>	
	</head>
	<body>
	       <div class="headerdiv">
<div id="freniz-logo" style="width:220px; float:left; height:60px; ">
    <a style="text-decoration:none; cursor: pointer; "href="#"><img src="http://localhost/freniz_zend/public/images/freniz.png"/></a>
</div>
<div id="smile-mood-change" style="width:40px; float:left; height:80px; ">
   <div class="moody" style="width:40px; margin-top: 10px; float:left; height:40px; "><img id="top-smiley" style="cursor: pointer;marin-top:10px" src="http://localhost/freniz_zend/public/images/mood/32/<?php $smood=explode(',', $session['mood']); echo $smood[0];?>" width="40" height="40"/></div>
<span-edit>
Click to Change
</span-edit>
<div style="position:absolute">
  <span-smiley style="background:none;" id="mood-smile" >


</span-smiley>
  </div>  
</div>
<div id="top-menu-items" style=" float:left; height:80px; ">
<div style="height:30px; margin-top: 15px; margin-left: 30px;  float:left; ">
    
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/streams">Stream</a></li>
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/<?php echo $session['userid']; ?>">Bio</a></li>
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/messages">Message</a></li>
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/blog/<?php echo $session['userid']; ?>">Blog</a></li>
	
	<li class="link-bord">
		<a href="#">Alert</a>
				<ul style=" margin-top: -5px;">
					<li><a href="#">Notifications</a></li>
					<li><a href="invitations.php">Invites</a></li>
					<li><a href="#">Reviews</a></li>
				</ul>				
	</li>
	<li class="link-bord">
		<a href="#">Apps</a>	
		<ul style=" margin-top: -5px;">
					 <li ><a href="http://www.freniz.com/forum">Forum</a></li>
                    <li><a href="http://www.freniz.com/diary">Diary</a></li>
					<li><a href="http://www.freniz.com/slambook">Slam book</a></li>
					<li><a href="#">Musics</a></li>
				</ul>		
	</li>
	
</ul>


</div>

</div>
<div style=" width: 250px; margin-right: 10px; float:right; height:80px; ">
<div id="accout-name-settings" style=" float:right; font-weight: bold; color: #fff; height:40px;">
   
 <nav>
           <ul>
		<li id="settings">
			<a id="acount-trigger-setting" href="javascript:0" class="active">
				<?php echo  $session['username']; ?> <span id="logspan">&#x25BC;</span>
			</a>
			<div id="acount-content-setting" >
                            <ul>
                                  <label style="color:#999; font-size: 18px; font-weight: bold">Freniz Account</label>
                                <li><a href="http://www.freniz.com/accountsettings">Account Settings</a></li>
                                 <li><a href="#">Privacy Setting</a> </li>
                                 <li><a href="#">Help</a></li>
                                 <li><a href="http://www.freniz.com/index/logout">Take Out</a> </li>
                            </ul>
			</div>                     
		</li>
                
            </ul>
        </nav>

    
 
</div>
<div id="search-option-items" style="width:200px; margin-top: -10px; float:right; height:20px; ">
    <input class="search-box" id="searchusers"  type="text" placeholder="search" onfocusout="searchitemsout(this)" onfocus="searchitemsin(this)" style="width:200px; height:20px" ><span id="search-top-loading" style="margin-top:-18px; margin-left: 165px; color: #ffffff; display: none; position: absolute;"><img src="images/blackloading.gif" height="16" width="16"/></span></input>
    <span style="color:#ccc; cursor: pointer; font-size: 12px; float: right; margin-top: -18px; margin-right:6px">&#x25BC;</span>
</div>
</div>


</div>
	<div style="width: 1000px;  margin-left:auto; margin-right:auto">
	<div style="width: 700px; border-right:solid 1px;float:left;">
	
	<div style="width: 500px; float:left;  border-bottom:solid 1px; padding:40px;">
	<div style="float:left;">
	<img   id="target" alt="Flowers" alt="Flowers" src="http://localhost/freniz_zend/public/images/500/500_<?php echo $this->results['url'];?>"></img>
	</div>
	
	
	<?php if($this->type=='propic'){?>
	<span style="float:right;margin-top:5px; display:none; " class="done-button" onclick="propiccroping('<?php echo $this->results['imageid']; ?>','true')" id="leaf-vote">done</span>
 <?php }elseif ($this->type=='secd_1'){?>
 	<span style="float:right;margin-top:5px; display:none " class="done-button" onclick="secpiccroping('<?php echo $this->results['imageid']; ?>','false','1')" id="leaf-vote">done</span>
<?php }?>
		<a style="float:right; margin-top:7px; text-decoration:none; color:#000; margin-right:5px" href="http://www.freniz.com/<?php echo $session['userid'];?>">-->Home</a>	
	<span style="float:left;margin-top:10px; margin-left:20px; " class="crop-button" id="leaf-vote">crop</span>
	
	<form id="coords" class="coords" onsubmit="return false;" >
	<div style="display:none">
	<input type="hidden" size="4" id="x1" name="x1" value="0" />
	<input type="hidden" size="4" id="y1" name="y1" value="0" />
	<input type="hidden" size="4" id="x2" name="x2" value="0" />
	<input type="hidden" size="4" id="y2" name="y2" value="0" />
	<input type="hidden" size="4" id="w" name="w" value="0" />
	<input type="hidden" size="4" id="h" name="h" value="0" />
	</div></form>
	</div>
	
	<script type="text/javascript">
	$('.crop-button').click(function(){

		initcrop(<?php echo $this->init;?>);
		$('.crop-button').css('display','none');
		$('.done-button').css('display','block');
	});
	 

	  function initcrop(aspectRatio){
	  	
		     var c=$('#target').Jcrop({
	          onChange:   showCoords,
	          onSelect:   showCoords,
	          onRelease:  clearCoords,
	          aspectRatio: aspectRatio
	        }).Coords;

	     
      }
	  function showCoords(c)
	    {
	        
	      $('#x1').val(c.x);
	      $('#y1').val(c.y);
	      $('#x2').val(c.x2);
	      $('#y2').val(c.y2);
	      $('#w').val(c.w);
	      $('#h').val(c.h);
	    };

	    function clearCoords()
	    {
	      $('#coords input').val('');
	      $('#h').css({color:'red'});
	      window.setTimeout(function(){
	        $('#h').css({color:'inherit'});
	      },500);
	    };
	</script>
	
	</div>
	<div style="width:250px; margin-left:10px; height:100px; float:left; border:Solid 1px"></div>
	
	<div style="width:100%; height:100px; float:left; "></div>
	
	
	</div>
	
		<div id="musictab">

 <div class="foot-tab">
     <ul>
        <li><a href="#">About</a></li>
         <li><a href="http://www.freniz.com/search">Search</a></li>
         <li><a href="#">Terms</a></li>
         <li><a href="#">Privacy</a></li>
         <li><a href="#">Help</a></li>
         <li><a href="http://www.freniz.com/createleaf">Create a leaf</a></li>
          <li><a href="http://www.freniz.com/developers">Developers</a></li>
         <li><a href="http://www.freniz.com/hireus">Hire Us</a></li>
     </ul>
     
 </div> 
       
</div>
	
	
	</body>

</html>
