<?php
header("Cache-Control: no-cache, must-revalidate" );
header("Pragma: no-cache" );
header("Content-Type: text/xml; charset=utf-8");
?>
<comments>
	<imageid><?php echo $this->imageid;?></imageid>
	<?php reset($this->results); $key=key($this->results); ?>
	<totalcomments><?php echo $this->results[$key]['commentcount'];?></totalcomments>
	<maxcomment><?php echo $this->maxcomment;?></maxcomment>
	<?php foreach($this->results as $commentid=>$values){?>
	<comment>
		<id><?php echo $commentid; ?></id>
		<username><?php echo $values['username']; ?></username>
		<user_url><?php echo $values['url']; ?></user_url>
		<imageurl><?php echo $values['user_imgurl']; ?></imageurl>
		<comment-comment><?php echo $values['comment']; ?></comment-comment>
		<date><?php echo $values['date'];?></date>
	</comment>
	<?php } ?>
</comments>