
<?php 
 
      $images=$this->results['results']['images'];
       krsort($images);
      $session=(array)$this->mydetails;
		//print_r($images);
?>
<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8">
		<title>Image Gallery</title>
		<link rel="stylesheet" href="http://localhost/freniz_zend/public/css/default.css" type="text/css" media="screen" charset="utf-8" />
		<link rel="stylesheet" href="http://localhost/freniz_zend/public/css/galleriffic-5_1.css" type="text/css" />
		<link rel="stylesheet" href="http://localhost/freniz_zend/public/css/black.css" type="text/css" />
		<link rel="stylesheet" href="http://localhost/freniz_zend/public/css/autosuggest_inquisitor.css" type="text/css" media="screen" charset="utf-8" />
		<script type="text/javascript" src="http://localhost/freniz_zend/public/js/jquery-latest.js"></script>
		<script type="text/javascript" src="http://localhost/freniz_zend/public/js/ajax.js"></script>
        <script type="text/javascript" src="http://localhost/freniz_zend/public/js/jquery.history_1.js"></script>
		<script type="text/javascript" src="http://localhost/freniz_zend/public/js/jquery.galleriffic_1.js"></script>
		<script type="text/javascript" src="http://localhost/freniz_zend/public/js/jquery.opacityrollover.js"></script>
		    <script src="http://localhost/freniz_zend/public/js/jquery.timeago.js" type="text/javascript"></script>
	 <script type="text/javascript" src="http://localhost/freniz_zend/public/js/leaf.js"></script>
		
		        <!-- We only want the thunbnails to display when javascript is disabled -->
		<script type="text/javascript" src="http://localhost/freniz_zend/public/js/bsn.AutoSuggest_c_2.0.js"></script>
                <script type="text/javascript">
			document.write('<style>.noscript { display: none; }</style>');
		</script>
                <style>  
body{
   width: 99%;
   font-family: arial, helvetica, geneva, sans-serif;
   margin-left:1px;
   margin-top:0px;
}

                    #commentbox {
       float:left;
	overflow: auto;
}
#pin-done{
	cursor: pointer;
			  font-weight: bold;
			  padding: 3px 10px;
			  text-decoration: none;
			  color: #000;
			  text-shadow: 0 1px 0 #fff; 
			  -moz-border-radius: 6px;
			  -webkit-border-radius: 6px;
			  border-radius: 6px;
	                  background-color: rgb(146,213,0);
			  background-image: -webkit-gradient(linear, left top, left bottom, from(rgb(146,213,0)), to(rgb(146,213,0)));
			  background-image: -webkit-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: -moz-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: -ms-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: -o-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
	                   -webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	-ms-box-sizing: border-box;
	-o-box-sizing: border-box;
	box-sizing: border-box;
	-webkit-box-shadow: 0 1px 0 rgba(255, 255, 255, 0.07),0 1px 0 rgba(255, 255, 255, 0.07) inset;
	-moz-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
	-ms-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
	-o-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
	box-shadow: 0 1px 0 rgba(255, 255, 255, 0.07),0 1px 0 rgba(255, 255, 255, 0.07) inset;
}
 .usersname{
                		font-size:9px;
	                    background-color:#ccc;
	                    float:left;
	                    padding:2px;
	                    margin-left:2px;
	                    border:  solid 1px;
                }
                
#option ul,.option ul{
			display:inline;
		
		}
		#option,.option{
		width:150px;
		position:absolute;
		background-color:#ccc;
		 -moz-box-shadow: 0px 0px 5px 5px rgba(152,164,238,1.3);
	        -webkit-box-shadow: 0px 0px 5px 5px rgba(152,164,238,1.3);
	        -ms-box-shadow: 0px 0px 5px 5px rgba(152,164,238,1.3);
	        box-shadow: 1px 1px 2px 2px rgba(152,164,238,1.3);
		}
		#option ul li,.option ul li{
			display:block;
		width:144px;
		
			padding:2px;
	
		}
		#option ul li:hover,.option ul li:hover{
			display:block;
		background-color:#eee;
		cursor:pointer;
		}
		
		#option ul li a,.option ul li a{
			width:200px;
			padding:2px;
		color:#000;
			
		}
      .crop{
            
	float: right;      
display: inline-block;
margin-left: 50px;
cursor: pointer;
line-height: 25px;
font-weight: bold;
padding: 6px 40px;
text-decoration: none;
color: black;
text-shadow: 0 1px 0 white;
-moz-border-radius: 6px;
-webkit-border-radius: 6px;
border-radius: 6px;
background-color: #92D500;
background-image: -webkit-gradient(linear, left top, left bottom, from(#92D500), to(#92D500));
background-image: -webkit-linear-gradient(top, #92D500, #92D500);
background-image: -moz-linear-gradient(top, #92D500, #92D500);
background-image: -ms-linear-gradient(top, #92D500, #92D500);
background-image: -o-linear-gradient(top, #92D500, #92D500);
background-image: linear-gradient(top, #92D500, #92D500);
-webkit-box-sizing: border-box;
-moz-box-sizing: border-box;
-ms-box-sizing: border-box;
-o-box-sizing: border-box;
box-sizing: border-box;
-webkit-box-shadow: 0 1px 0 rgba(255, 255, 255, 0.07),0 1px 0 rgba(255, 255, 255, 0.07) inset;
-moz-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
-ms-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
-o-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
box-shadow: 0 1px 0 rgba(255, 255, 255, 0.07),0 1px 0 rgba(255, 255, 255, 0.07) inset;
}
 
</style>


	</head>
        
	<body>
  <img id="loading" src="images/prettyGallery/loading-gif-animation.gif" style="position:absolute; display: none; margin-left: 45%" height="32" width="32"></img>
    <div class="headerdiv">
<div id="freniz-logo" style="width:220px; float:left; height:60px; ">
    <a style="text-decoration:none; cursor: pointer; "href="#"><img src="http://localhost/freniz_zend/public/images/freniz.png"/></a>
</div>
<div id="smile-mood-change" style="width:40px; float:left; height:60px; ">
<?php if(isset($session['userid']) && $session['type']!='none' && $session['type']!='leaf'){ ?>
   <div style="width:40px; margin-top: 10px; float:left; height:40px; "><img id="top-smiley" style="cursor: pointer;marin-top:10px" src="http://localhost/freniz_zend/public/images/mood/32/<?php $smood=explode(',', $session['mood']); echo $smood[0];?>" width="40" height="40"/></div>
<?php } ?>
</div>
<div id="top-menu-items" style=" float:left; height:60px; ">
<div style="height:30px; margin-top: 15px; margin-left: 30px;  float:left; ">
    <?php if(isset($session['userid']) && $session['type']=='user'){ ?>
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="http://localhost/freniz_zend/public/">Stream</a></li>
	<li class="link-bord" id="top-underline"><a href="http://localhost/freniz_zend/public/<?php echo $session['userid']; ?>">Bio</a></li>
	<li class="link-bord" id="top-underline"><a id="mes-a" href="http://localhost/freniz_zend/public/messages">Message</a></li>
	<li class="link-bord" id="top-underline"><a href="http://localhost/freniz_zend/public/blog/<?php echo $session['userid']; ?>">Blog</a></li>
	
	<li class="link-bord">
		<a id="alert-a" href="#">Alert</a>
				<ul style=" margin-top: -5px;">
					<li><a id="noti-a" href="http://localhost/freniz_zend/public/notification">Notifications</a></li>
					<li><a id="revi-a" href="http://localhost/freniz_zend/public/review/reviews">Reviews</a></li>
				</ul>				
	</li>
	<li class="link-bord">
		<a href="#">Apps</a>	
		<ul style=" margin-top: -5px;">
					 <li ><a href="http://localhost/freniz_zend/public/forum">Forum</a></li>
                    <li><a href="http://localhost/freniz_zend/public/diary">Diary</a></li>
					<li><a href="http://localhost/freniz_zend/public/slambook">Slam book</a></li>
				</ul>		
	</li>
	
</ul>
<?php }else{ ?>
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="http://localhost/freniz_zend/public/<?php echo $session['userid']; ?>">Home</a></li>
<ul>

<?php } ?>
</div>

</div>
<div style=" width: 250px; margin-right: 10px; float:right; height:60px; ">
<?php if($session['userid']){ ?> 
<div id="accout-name-settings" style=" float:right; font-weight: bold; color: #fff; height:40px;">
   
 <nav>
           <ul>
		<li id="settings">
			<a id="acount-trigger-setting" href="javascript:void(0)" title="<?php echo $session['username']; ?>" class="active">
				<?php 
				$name = $session['username'];
                 if(strlen($name) > 24 )
                 {
                 echo substr($name, 0, 26).'...' ;
                                 }
               else {
                   echo $name;
               } ?> <span id="logspan">&#x25BC;</span>
			</a>
			<div id="acount-content-setting" >
                            <ul>
                                <label style="color:#999; font-size: 18px; font-weight: bold">Freniz Account</label>
                                <?php 
                                $val=$session['adminpages_details'];
                                unset($val[$session['userid']]);
                                foreach ($val as $value){
                                	?>
                            		<li title="<?php echo $value['username']; ?>" onclick="switchuser('<?php echo $value['userid'];?>')"  ><div style="border-bottom:solid 1px #ccc; padding:3px; height:16px"><label  style="color:#999; height:16px;float:left;font-weight: bold"><img style="width:16px; height:16px; float:left" src="http://localhost/freniz_zend/public/images/32/32_<?php echo $value['propic_url'];?>"/><a title="<?php echo $value['username']; ?>" style="font-size:10px;padding-left:4px;"><?php $leafname = $value['username'];
                 if(strlen($leafname) > 15 )
                 {
                 echo substr($leafname, 0, 15).'...' ;
                                 }
               else {
                   echo $leafname; } ?></a></label></div></li>
                                 	<?php } 
                                 	if($session['type']!='none' && $session['type']!='leaf'){
                                 	?>
                                 	 <li ><a href="http://localhost/freniz_zend/public/index/personalinfo?log_aug=finis">Account Settings</a></li>
                                 <li><a href="http://localhost/freniz_zend/public/index/privacysettings">Privacy Setting</a> </li>
                                <?php }elseif($session['type']=='leaf'){ ?>
                                   <li><a href="http://localhost/freniz_zend/public/leafedit/<?php echo $session['userid']; ?>#privacyinfo">Privacy Setting</a> </li>
                                <?php } ?>
                                 <li><a href="#">Help</a></li>
                                 <li><a href="http://localhost/freniz_zend/public/index/logout">Take Out</a> </li>
                            </ul>
			</div>                     
		</li>
                
            </ul>
        </nav>

    
 
</div>
 <?php }else {?>
      <div style="width:250px; height: 40px; float:right">
             <a style=" padding:3px 10px; float:right" href="http://localhost/freniz_zend/public/loginattempt" id="leaf-vote">Login</a>
          </div>
    <?php } ?>
 
<div id="search-option-items" style="width:200px; margin-top: -10px;margin-right:50px;  float:right; height:20px; ">
    <input class="search-box" id="searchusers"  type="text" placeholder="search" onfocusout="searchitemsout(this)" onfocus="searchitemsin(this)" style="width:250px; height:30px" ><span id="searchusers-load" style="margin-top:-24px; margin-left: 215px; color: #ffffff; display: none; position: absolute;"><img src="images/blackloading.gif" height="16" width="16"/></span></input>
    <span style="color:#ccc; cursor: pointer; font-size: 12px; float: right; margin-top: -24px; margin-right:-45px">&#x25BC;</span>
</div>
</div>


</div> 
    
		<div  id="maincontainer" >
		
		<div  id="page" style="margin-top:5px;">
			<div id="container">
				
				<!-- Start Advanced Gallery Html Containers -->				
				<div class="navigation-container">
					<div id="thumbs" class="navigation">
						<a class="pageLink prev" style="visibility: hidden;" href="#" title="Previous Page"></a>
					
						<ul class="thumbs noscript">
                                                    <?php $i=0; foreach($images as $key => $image){  ?>
							<li>
							
								<a class="thumb"  name="<?php echo $key; ?>" href="http://localhost/freniz_zend/public/images/500/500_<?php echo $image['url'] ?>" title="<?php echo $image['title']; ?>">
                                                                  <img src="http://localhost/freniz_zend/public/images/75/75_<?php echo $image["url"]; ?>" height="75" width="75" alt="<?php echo $image["url"]; ?>" />
								 </a>
								<div class="caption" style="float: right">
									     <div style="width:360px; float:left; padding:10px; ">
		
																	<div style="width:360px; float:left; height:50px; ">
																	<div style="width:50px; float:left; height:50px;">
																	<img src="http://localhost/freniz_zend/public/images/50/50_<?php echo $image["surl"]; ?>" height="50" width="50" alt="<?php echo $image["surl"]; ?>" />
																	</div>
																	<div style="width:290px; padding:5px;  float:left;height:40px; ">
																	<label style="font-size:18px; font-weight:bold"><a href="http://localhost/freniz_zend/public/<?php echo $image["userid"]; ?>"><?php echo $image["username"]; ?></a></label><br/>
																	<?php echo $image['pt'];?>
																	</div>
																	</div>
																	<div style="width:340px; padding:5px;  float:left; ">
																	<label style="font-size:24px; font-weight:bold">Story...</label>
																	<span class="timeago" title="<?php echo $image["date"]; ?>"><?php echo $image["date"]; ?></span>
																	 <?php if($image['userid']==$session['userid']){?>
																	 <a style="float:right" id="edit-setting"href="javascript:0">Edit</a>
																	 <div style="float:right;margin-top:18px;" id="edit-set" ></div>
																	<?php }?>
																	<div id="image-desc" style="width:320px; font-size:18px; padding:5px; color:#444;  float:left; ">
																	<?php echo $image["description"]; ?>
																	</div>
																	</div>
																	<div id="<?php echo $key; ?>_pinnedpeople_list" style="width:340px; padding:5px;  float:left; ">
																	</div>
																	<input type="hidden" id="<?php echo $key; ?>_pinnedpeople_hidden"/>
																	<div style="width:340px; cursor:pointer; padding:3px; float:left; ">
																	<div><?php $vote=unserialize($image['vote']);
																	  $votecount=count($vote);
																	  if(!in_array($session['userid'], $vote)){
																	?>
																	<a onclick="voteimage(<?php echo $key;?>,this)"style="float:right; text-decoration:none;">wink( <?php echo $votecount; ?> )</a>
																	<?php }else{?>
																	<a onclick="unvoteimage(<?php echo $key;?>,this)" style="float:right; text-decoration:none; ">winked( <?php echo $votecount; ?> )</a>
																	<?php }?></div><span style="float:right;padding-right:5px;">-</span>
																	<a id="pin-int"onclick="addpin('<?php echo $key;?>')" style="float:right; padding-right:5px;text-decoration:none;">pin</a>
																	 <a id="option-select"href="javascript:0">option</a><input type="hidden" id="imgid" value="<?php echo $key;?>"/><input type="hidden" id="albumname" value="<?php echo $image["name"];?>"/>
									                                  <input type="hidden" id="image-userid" value="<?php echo $image['userid'];?>" />  
																	<div id="pin-req" >
																	</div>
																	
																	</div>
																	
																	</div>			
                                                                    <div style="width:360px; margin-top: -3px; float:left; border:solid beige 1px;"></div>
                                                                    <div style="color:white; font-size:20px; width:300px; float:left"> <?php echo " Photo ".++$i." of ".  count($images); ?></div>
                                                                     <div style="width:250px;float:left; height: 200px; border: solid 1px #009F00; "></div></div>
                                                             <div class="comment">
									       <?php if($image['iscommentable']==1){?>
         <div  style="padding:10px; background-color:#eee; float:left; width:500px; ">
             <input id="<?php echo $key; ?>_comment" onkeyup="doimagecomment('<?php echo $key; ?>',event)" autocomplete="off" placeholder="write your comments" style="width:500px; height:30px" name="comment"/>
          </div>    
			<div id="<?php echo $key; ?>_com" style="overflow: auto; width: 100%;  float: left; ">					 
                        </div>
                 <?php }else echo '<center>you cannot comment to this photo</center>';?>
								</div>
							</li>
							
	  <?php } ?>
							
						</ul>
						<a class="pageLink next" style="visibility: hidden;" href="#" title="Next Page"></a>
					</div>
				</div>
				<div class="content">
					<div class="slideshow-container">
					
						  <?php   if (count($images)!=1){  ?>
						<div id="controls" class="controls"></div><?php } ?>
						<div id="loading" class="loader"></div>
						<div id="slideshow" class="slideshow"></div>
					</div>
					<div id="caption" class="caption-container">
                                           
                                                
					</div>
				</div>
                                 <div id="comment" class="comment-container">
                                 </div>  
				<!-- End Gallery Html Containers -->
				<div style="height:100px; width:1000px; float:left; "></div>
			</div>
		</div>
		
		</div>
		
		<div id="musictab">

 <div class="foot-tab">
     <ul>
         <li><a href="#">About</a></li>
         <li><a href="#">Search</a></li>
         <li><a href="#">Terms</a></li>
         <li><a href="#">Privacy</a></li>
         <li><a href="#">Help</a></li>
         <li><a href="#">Create a leaf</a></li>
          <li><a href="#">Developers</a></li>
         <li><a href="#">Hire Us</a></li>
     </ul>
     
 </div> 
       
</div>
		<script type="text/javascript">
			jQuery(document).ready(function($) {
				prettyLinks();
				// We only want these styles applied when javascript is enabled
				$('div.content').css('display', 'block');

				// Initially set opacity on thumbs and add
				// additional styling for hover effect on thumbs
				var onMouseOutOpacity = 0.67;
				$('#thumbs ul.thumbs li, div.navigation a.pageLink').opacityrollover({
					mouseOutOpacity:   onMouseOutOpacity,
					mouseOverOpacity:  1.0,
					fadeSpeed:         'fast',
					exemptionSelector: '.selected'
				});
				
				// Initialize Advanced Galleriffic Gallery
				var gallery = $('#thumbs').galleriffic({
					delay:                     2500,
					numThumbs:                 10,
					preloadAhead:              10,
					enableTopPager:            false,
					enableBottomPager:         false,
					imageContainerSel:         '#slideshow',
					controlsContainerSel:      '#controls',
					captionContainerSel:       '#caption',
                    commentContainerSel:       '#comment',
					loadingContainerSel:       '#loading',
					renderSSControls:          true,
					renderNavControls:         true,
					playLinkText:              'Play Slideshow',
					pauseLinkText:             'Pause Slideshow',
					prevLinkText:              '&lsaquo; Previous Photo',
					nextLinkText:              'Next Photo &rsaquo;',
					nextPageLinkText:          'Next &rsaquo;',
					prevPageLinkText:          '&lsaquo; Prev',
					enableHistory:             true,
					autoStart:                 false,
					syncTransitions:           true,
					defaultTransitionDuration: 900,
					onSlideChange:             function(prevIndex, nextIndex) {
						// 'this' refers to the gallery, which is an extension of $('#thumbs')
						this.find('ul.thumbs').children()
							.eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
							.eq(nextIndex).fadeTo('fast', 1.0);

						// Update the photo index display
						this.$captionContainer.find('div.photo-index')
							.html('Photo '+ (nextIndex+1) +' of '+ this.data.length);
					},
					onPageTransitionOut:       function(callback) {
						this.fadeTo('fast', 0.0, callback);
					},
					onPageTransitionIn:        function() {
						var prevPageLink = this.find('a.prev').css('visibility', 'hidden');
						var nextPageLink = this.find('a.next').css('visibility', 'hidden');
						
						// Show appropriate next / prev page links
						if (this.displayedPage > 0)
							prevPageLink.css('visibility', 'visible');

						var lastPage = this.getNumPages() - 1;
						if (this.displayedPage < lastPage)
							nextPageLink.css('visibility', 'visible');

						this.fadeTo('fast', 1.0);
					}
				});

				/**************** Event handlers for custom next / prev page links **********************/

				gallery.find('a.prev').click(function(e) {
					gallery.previousPage();
					e.preventDefault();
				});

				gallery.find('a.next').click(function(e) {
					gallery.nextPage();
					e.preventDefault();
				});
				
				/****************************************************************************************/

				/**** Functions to support integration of galleriffic with the jquery.history plugin ****/

				// PageLoad function
				// This function is called when:
				// 1. after calling $.historyInit();
				// 2. after calling $.historyLoad();
				// 3. after pushing "Go Back" button of a browser
				function pageload(hash) {
					// alert("pageload: " + hash);
					// hash doesn't contain the first # character.
					if(hash) {
						$.galleriffic.gotoImage(hash);
					} else {
						gallery.gotoIndex(0);
					}
				}

				// Initialize history plugin.
				// The callback is called at once by present location.hash. 
				$.historyInit(pageload, "advanced.html");

				// set onlick event for buttons using the jQuery 1.3 live method
				$("a[rel='history']").live('click', function(e) {
					if (e.button != 0) return true;

					var hash = this.href;
					hash = hash.replace(/^.*#/, '');

					// moves to a new page. 
					// pageload is called at once. 
					// hash don't contain "#", "?"
					$.historyLoad(hash);

					return false;
				});
			   
				/****************************************************************************************/

			   
					   
				
				 
				});
			
		</script>
                <script type="text/javascript">
				
                getcount();	
                                
                var suserid="<?php echo $session['userid'];?>";
					function addpin(id){
						var imageuserid=$('#image-userid').val();
						if(suserid==imageuserid){
							var pin='<div id="pin-div" style="padding:10px; position:absolute; margin-left:-10px; margin-top:-10px; width:260px; background-color:#eee;"><input id="'+id+'_pinnedpeople"placeholder="search your friends to pin"type="text"style="width:200px; height:25px;"/><span style="float:right; " onclick="$(\'#pin-div\').remove(); pinpeople(\''+id+'\')"id="pin-done">done</span></div>';
							 $('#pin-req').html(pin);
							 var as_search=new AutoSuggest(id+'_pinnedpeople', options_xmlsearch('friends'));  
						}else{
							pinme(id);
							}
							  
					}
					
					$('#edit-setting').live('click',function(){
						var imgid=$('#imgid').val();
						var a='<div class="option"style="margin-left:-100px"><ul><li id="edit-desc"><a>edit story</a></li><li id="privacy-set" ><a>edit privacy</a></li></ul></div>';
						$('#edit-set').html(a);
						$(".option").mouseover(function() {
						    $('.option').css('display','block');
						  }).mouseout(function(){
							  $('.option').css('display','none');
						  });
						});
					$('#edit-desc').live('click',function(){
						var a='<div id="edit-div" style="padding:10px; position:absolute; margin-left:-200px; margin-top:-10px; width:260px; background-color:#eee;"><textarea  id="edit-desc-text"placeholder="write story..."style="width:250px; height:50px;"></textarea><span style="float:right;margin-top:3px;margin-right:5px;" onclick="adddescription();$(\'#edit-div\').remove(); "id="pin-done">update</span><span style="float:right;margin-top:3px; margin-right:5px; " onclick="$(\'#edit-div\').remove(); "id="pin-done">cancel</span></div>';
						$('#edit-set').html(a);
						});
					$('#option-select').live('click',function(){
						var imgid=$('#imgid').val();
						var albumname=$('#albumname').val();
						var imageuserid=$('#image-userid').val();
						var a='<div id="option"style=""><ul><li id="propic-set" onclick="setaspropic(\''+imgid+'\',false)"><a>set this profile</a></li><li id="walpic-set" onclick="setassecpic(\''+imgid+'\',\'false\',\'1\')"><a>set this wallpic</a></li><li id="delete-set"onclick="deleteimage(\''+imgid+'\')"><a>delete</a></li><li><a>report</a></li></ul></div>';
						$('#pin-req').html(a);
						if(suserid==imageuserid){
						if(albumname=='Secondary Pics'){
							$('#propic-set').remove();}
						else if(albumname=='Profile Pics' ){
								$('#walpic-set').remove();}
						else{
							$('#walpic-set a').attr("href","http://localhost/freniz_zend/public/crop/"+imgid+"?type=secd_1");
								$('#propic-set a').attr("href","http://localhost/freniz_zend/public/crop/"+imgid+"?type=propic");
								$('#wallpic-set').removeAttr("onclick");		
								$('#propic-set').removeAttr("onclick");
								}
						}else{
							$('#propic-set').remove();$('#walpic-set').remove();$('#delete-set').remove();
						}
						$("#option").mouseover(function() {
						    $('#option').css('display','block');
						  }).mouseout(function(){
							  $('#option').css('display','none');
						  });
						});

					
					var options_xmlsearch = function(type,appendto){
			         	if(!appendto)
			            appendto='body'; 
			            var options={
			                    script:"http://localhost/freniz_zend/public/search?type="+type+"&",
			    				varname:"key",
			                    type:type,
		                   		appendto:appendto,
			                    callback:function(suggestion,fld){
			                      //  for(var i in suggestion)
			                        //    alert(i+"=>"+suggestion[i]);
			                        		
			                        		if(!$('div [name='+suggestion.id+']').is('*')){
			                            			 var e=document.createElement('div');
				                 						e.className='usersname';
				                 	                    $(e).attr('name',suggestion.id);
				                 	                    e.innerHTML=suggestion.name+'<a style="width:10px; height:10px; text-decoration:none; background-color:red; font-size:14px; margin-bottom:20px" onclick="alert(this.innerHTML);$(this).parent().remove();" href="javascript:void(0)">x</a>';
				                 						$('#'+fld.id+'_list').append(e);
				                 						$('#'+fld.id).val('');
			                        		}
			                        		else
			                            		alert('already exists');
			    					   }
			                    
			               	 };
			              	  return options;
			    			}
        		var as_xmlsearch = new AutoSuggest('searchusers', options_xmlsearch('all'));
</script>
 <div id="light" style="border:solid 1px yellow" class="white_conten"></div>
<div id="fade" onClick="document.getElementById('light').style.display='none';  document.getElementById('fade').style.display='none'" class="black_overla">
 </div>
	</body>
</html>
