<?php 
		$ud=$this->userdetails;
		$session=(array)$this->mydetails;

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Add slambook</title>
<link rel="stylesheet" href="http://localhost:10088/freniz_zend/public/css/default.css" type="text/css" media="screen" charset="utf-8" />
<link rel="stylesheet" href="http://localhost:10088/freniz_zend/public/css/theme.css" type="text/css" media="screen" charset="utf-8" />
<script type="text/javascript" src="http://localhost:10088/freniz_zend/public/js/jquery.js"></script> 
<script src="http://localhost:10088/freniz_zend/public/js/ajax.js" type="text/javascript"></script>
<script type="text/javascript" src="http://localhost:10088/freniz_zend/public/js/unserialize.js"></script>
	          <script type="text/javascript" src="http://localhost:10088/freniz_zend/public/js/leaf.js"></script> 

<style>
td,textarea{
	font-size:20px;
	font-weight:bold;
}

#leaf-vote{
	            
	    	  cursor: pointer;
			  font-weight: bold;
			  padding: 6px 40px;
			  text-decoration: none;
			  color: #000;
			  text-shadow: 0 1px 0 #fff; 
			  -moz-border-radius: 6px;
			  -webkit-border-radius: 6px;
			  border-radius: 6px;
	                  background-color: rgb(146,213,0);
			  background-image: -webkit-gradient(linear, left top, left bottom, from(rgb(146,213,0)), to(rgb(146,213,0)));
			  background-image: -webkit-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: -moz-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: -ms-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: -o-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
	                   -webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	-ms-box-sizing: border-box;
	-o-box-sizing: border-box;
	box-sizing: border-box;
	-webkit-box-shadow: 0 1px 0 rgba(255, 255, 255, 0.07),0 1px 0 rgba(255, 255, 255, 0.07) inset;
	-moz-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
	-ms-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
	-o-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
	box-shadow: 0 1px 0 rgba(255, 255, 255, 0.07),0 1px 0 rgba(255, 255, 255, 0.07) inset;
	        
	        }
#slam-title{
            	     border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 0 0 10px 10px;
             -moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        -webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
	        -ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);
            background-color:#eee;
           
            }
</style>
<script type="text/javascript">

function addslambook(userid)
{
	 var name=escape(document.getElementById('name').value);
    var bday=escape(document.getElementById('born').value);
    var email=escape(document.getElementById('email').value);
    var phone=escape(document.getElementById('ring').value);
    var ambition=escape(document.getElementById('ambition').value);
    var hobby=escape(document.getElementById('hobby').value);
    var believe=escape(document.getElementById('believe').value);
    var friendship=escape(document.getElementById('friendship').value);
    var love=escape(document.getElementById('love').value);
    var hate=escape(document.getElementById('hate').value);
    var philosophy=escape(document.getElementById('philosophy').value);
    var film=escape(document.getElementById('film').value);
    var music=escape(document.getElementById('music').value);
    var actor=escape(document.getElementById('actor').value);
    var actress=escape(document.getElementById('actress').value);
    var sports=escape(document.getElementById('sports').value);
    var sportsman=escape(document.getElementById('sportsman').value);
     var dress=escape(document.getElementById('dress').value);
    var food=escape(document.getElementById('food').value);
    var place=escape(document.getElementById('place').value);
    var friends=escape(document.getElementById('friends').value);
    var feel=escape(document.getElementById('feel').value);
    var advice=escape(document.getElementById('advice').value);
    var parameters="userid="+userid+"&Name="+name+"&Born On="+bday+"&Email="+email+"&Ring Me="+phone+"&Ambition="+ambition+"&My Hobby="+hobby+"&I Believed in="+believe+"&About Friendship="+friendship+"&About Love="+love+"&I hate="+hate+"&My Philosophy="+philosophy+"&Fav Film="+film+"&Fav Music="+music+"&Fav Actor="+actor+"&Fav Actress="+actress+"&Fav Sports="+sports+"&Fav Sportsman="+sportsman+"&Fav Dress="+dress+"&Fav Food="+food+"&Fav Place="+place+"&Close Friends="+friends+"&I Feel About You="+feel+"&My Advice for You="+advice;
    $.ajax({
		url:'http://localhost:10088/freniz_zend/public/updateslambook',
		cache:false,
		data:parameters,
		type:'post',
		dataType:"json",
		success:function(json){
					alert(json.status);
			}
    });   
}

</script>
</head>

<body>
<div class="headerdiv">
<div id="freniz-logo" style="width:220px; float:left; height:60px; ">
    <a style="text-decoration:none; cursor: pointer; "href="#"><img src="images/freniz.png"/></a>
</div>
<div id="smile-mood-change" style="width:40px; float:left; height:80px; ">
   <div class="moody" style="width:40px; margin-top: 10px; float:left; height:40px; "><img id="top-smiley" style="cursor: pointer;marin-top:10px" src="images/mood/32/<?php $smood=explode(',', $session['mood']); echo $smood[0];?>" width="40" height="40"/></div>
<span-edit>
Click to Change
</span-edit>
<div style="position:absolute">
  <span-smiley style="background:none;" id="mood-smile" >


</span-smiley>
  </div>  
</div>
<div id="top-menu-items" style=" float:left; height:80px; ">
<div style="height:30px; margin-top: 15px; margin-left: 30px;  float:left; ">
    
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="streams.php">Stream</a></li>
	<li class="link-bord" id="top-underline"><a href="<?php echo $session['userid']; ?>">Bio</a></li>
	<li class="link-bord" id="top-underline"><a href="http://localhost:10088/freniz_zend/public/messages">Message</a></li>
	<li class="link-bord" id="top-underline"><a href="http://localhost:10088/freniz_zend/public/blog/<?php echo $session['userid']; ?>">Blog</a></li>
	
	<li class="link-bord">
		<a href="#">Alert</a>
				<ul style=" margin-top: -5px;">
					<li><a href="#">Notifications</a></li>
					<li><a href="invitations.php">Invites</a></li>
					<li><a href="#">Reviews</a></li>
				</ul>				
	</li>
	<li class="link-bord">
		<a href="#">Apps</a>	
		<ul style=" margin-top: -5px;">
					 <li ><a href="http://localhost:10088/freniz_zend/public/forum">Forum</a></li>
                    <li><a href="dairy.php">Diary</a></li>
					<li><a href="slambook.php?userid=<?php echo $session['userid']; ?>">Slam book</a></li>
					<li><a href="#">Musics</a></li>
				</ul>		
	</li>
	
</ul>


</div>

</div>
<div style=" width: 250px; margin-right: 10px; float:right; height:80px; ">
<div id="accout-name-settings" style=" float:right; font-weight: bold; color: #fff; height:40px;">
   
 <nav>
           <ul>
		<li id="settings">
			<a id="acount-trigger-setting" href="javascript:0" class="active">
				<?php echo  $session['username']; ?> <span id="logspan">&#x25BC;</span>
			</a>
			<div id="acount-content-setting" >
                            <ul>
                                  <label style="color:#999; font-size: 18px; font-weight: bold">Freniz Account</label>
                                <li><a href="http://localhost:10088/freniz_zend/public/accountsettings">Account Settings</a></li>
                                 <li><a href="#">Privacy Setting</a> </li>
                                 <li><a href="#">Help</a></li>
                                 <li><a href="http://localhost:10088/freniz_zend/public/index/logout">Take Out</a> </li>
                            </ul>
			</div>                     
		</li>
                
            </ul>
        </nav>

    
 
</div>
<div id="search-option-items" style="width:200px; margin-top: -10px; float:right; height:20px; ">
    <input class="search-box" id="searchusers"  type="text" placeholder="search" onfocusout="searchitemsout(this)" onfocus="searchitemsin(this)" style="width:200px; height:20px" ><span id="search-top-loading" style="margin-top:-18px; margin-left: 165px; color: #ffffff; display: none; position: absolute;"><img src="images/blackloading.gif" height="16" width="16"/></span></input>
    <span style="color:#ccc; cursor: pointer; font-size: 12px; float: right; margin-top: -18px; margin-right:6px">&#x25BC;</span>
</div>
</div>


</div>  



<div style="width:1000px; margin-left:auto; margin-right:auto;">
<?php if($ud){?>
<div id="slam-title" style="width: 980px; padding:10px;height:120px; ">
<label style="font-size: 20px; float:left; font-weight:bold;">You are writing slambook to <a style="text-transform: uppercase;"href="<?php echo $ud['userid'];?>"><?php echo $ud['username'];?></a></label>
<div style="width: 100px; height:100px;float:right; border:solid 1px;">
 <img id="profilepic" src='http://localhost:10088/freniz_zend/public/images/200/200_<?php echo $ud['propic_url'] ?>' height="100" width="100" />
</div>
</div>
<table style="margin-left:auto; margin-top:10px; margin-right:auto;" cellspacing="3" cellpadding="3">
<tr><td>Name</td><td><textarea id='name' style="width:600px; outline:none; height:30px"></textarea></td></tr>
<tr><td>Born on</td><td><textarea id='born' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Email</td><td><textarea id='email' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Ring me</td><td><textarea id='ring' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Ambition</td><td><textarea id='ambition' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Hobby</td><td><textarea id='hobby' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>I Believe in</td><td><textarea id='believe' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>About Friendship</td><td><textarea id='friendship' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>About Love</td><td><textarea id='love' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>I hate</td><td><textarea id='hate' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>My Philosophy</td><td><textarea id='philosophy' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Favourite Film</td><td><textarea id='film' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Favourite Music</td><td><textarea id='music' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Favourite Actor</td><td><textarea id='actor' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Favourite Actress</td><td><textarea id='actress' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Favourite Sports</td><td><textarea id='sports' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Favourite Sportsman</td><td><textarea id='sportsman' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Favourite food</td><td><textarea id='food' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Favourite Dress</td><td><textarea id='dress' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Favourite Place</td><td><textarea id='place' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>Close Friends</td><td><textarea id='friends' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>I Feel About You</td><td><textarea id='feel' style="width:600px;outline:none; height:30px"></textarea></td></tr>
<tr><td>My Advice For You</td><td><textarea id='advice' style="width:600px;outline:none; height:30px"></textarea></td></tr>

</table>
<div style="width:990px; height:30px; border-top:solid 1px; padding:10px;">
    <span id="leaf-vote" onclick="addslambook('<?php echo $ud['userid']?>')" style="float:right">Update</span>
    </div>
<?php }else{ ?>

<label style="font-size: 28px; float:left; font-weight:bold">You are not a friend of this user.</label>

<?php }?>
</div>

</body>
</html>