
<?php
	$session=(array)$this->mydetails;
	$lists=$this->lists;
	if($lists['html'] !=''){   ?>
		
		// design if html file is available ---- include($list['html']); 
	<?php }
	else
	{ 
		//design for normal list
	
?>
	<html>
	    <head>
	    <title>List | Freniz</title>
	         <script type="text/javascript" src="http://js.freniz.com/jquery.js"></script> 
	        <script type="text/javascript" src="http://js.freniz.com/ajax.js"></script> 
	        <link rel="stylesheet" href="http://css.freniz.com/theme.css" type="text/css" media="screen" charset="utf-8" />
	        <link rel="stylesheet" href="http://css.freniz.com/default.css" type="text/css" media="screen" charset="utf-8" />
	          <script type="text/javascript" src="http://js.freniz.com/leaf.js"></script> 
	      <script src="http://js.freniz.com/jquery.timeago.js" type="text/javascript"></script>
	     <script type="text/javascript" src="http://js.freniz.com/bsn.AutoSuggest_c_2.0.js"></script>
<link rel="stylesheet" href="http://css.freniz.com/autosuggest_inquisitor.css" type="text/css" media="screen" charset="utf-8" />
 
        
         <script type="text/javascript">
			
	     $(document).ready(function(event){
	     
	     	$('#settings-leaf').live('click',function(){
		var a='<div class="option"style="margin-left:35px; margin-top:20px"><ul><li id="lists-id" data="<?php echo $_REQUEST["id"]; ?>" onclick=""><a onclick="deletelist()">delete</a></li></ul></div>';
		$('#settings-leaf-div').html(a);
		$(".option").mouseover(function() {
		    $('.option').css('display','block');
		  }).mouseout(function(){
			  $('.option').css('display','none');
		  });
		});

	     
	    	 $('.mes-text').live('mouseover', function() {
	    		    $('.mes-text').toggle(function() {
	    		    	$('#mes-text').css('display','block');
	    		    	$('.mes-text').html('cancel');
	    		    },function(){
	    		    	$('#mes-text').css('display','none');
	    		    	$('.mes-text').html('send text');
	    		    });
	    		});
	    		
	    		
	    		$('.hover').live('mouseover',function(){
	    			var data=$(this).attr('data');
	    			miniprofile(data,this);
	    			$(".hover-div").live('mouseover',function() {
	    			    $('.hover-div').css('display','block');
	    			  }).live('mouseout',function(){
	    				  $('.hover-div').css('display','none');
	    			  });
	    			}).live('mouseout',function(){
	    				 $('.hover-div').css('display','none');
	    			  });
	    	
	     });
	     function miniprofile(data,element){
				var position=$(element).offset();
				getminiprofile(data,position.top,position.left);
			}
	     </script>
	      <style>
#remove-items{
			border-radius: 10px;
-moz-border-radius: 10px;
-webkit-border-radius: 10px;
-moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
-webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
-ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);
		}
#remove-items ul{
		display:inline;
		width:70px;
            background-color:#eee;
		
	}
	#remove-items ul li{
		display:block;
		background-color:#FFF;
		padding:7px;
	
	background-color:#eee;
		
		
	}
	#remove-items ul li a{
		margin-top:-10px;
		text-decoration:none;
		color:black;
		position:absolute;
	font-size:12px;
		padding:2px;
	}
	#remove-items ul li a:hover{
		background-color:#A4A4A4;
		width:70px;
		display:block;
		color:#FFF;
		 -moz-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  -webkit-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);	
		padding:2px;
		
		
	}
#user-pic{
            	     border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
             -moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        -webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
	        -ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);		
	}
  #stature-stream{
            	     border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
             -moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        -webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
	        -ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);
            background-color:#eee;
           
            }
.vote-bar {
                text-decoration: none;
                cursor: pointer;
                font-size: 14px; font-weight: bold;
                color: #000;
            }
           .vote-bar :hover{
                color: #fff;
            }
            .close {
                text-decoration: none;
                cursor: pointer;
                font-size: 8px; font-weight: bold;
                color: #000;
            }
            .close:hover{
                color: #aaa;
            }
#leaf-vote{
	            
	    	  cursor: pointer;
			  font-weight: bold;
			  padding: 6px 20px;
			  text-decoration: none;
			  color: #000;
			  text-shadow: 0 1px 0 #fff; 
			  -moz-border-radius: 6px;
			  -webkit-border-radius: 6px;
			  border-radius: 6px;
	                  background-color: rgb(146,213,0);
			  background-image: -webkit-gradient(linear, left top, left bottom, from(rgb(146,213,0)), to(rgb(146,213,0)));
			  background-image: -webkit-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: -moz-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: -ms-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: -o-linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
			  background-image: linear-gradient(top, rgb(146,213,0), rgb(146,213,0));
	                   -webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	-ms-box-sizing: border-box;
	-o-box-sizing: border-box;
	box-sizing: border-box;
	-webkit-box-shadow: 0 1px 0 rgba(255, 255, 255, 0.07),0 1px 0 rgba(255, 255, 255, 0.07) inset;
	-moz-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
	-ms-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
	-o-box-shadow: 0 1px 0 rgba(255,255,255,0.07),0 1px 0 rgba(255,255,255,0.07) inset;
	box-shadow: 0 1px 0 rgba(255, 255, 255, 0.07),0 1px 0 rgba(255, 255, 255, 0.07) inset;
	        
	        }
	        #leaf-vote:hover{
	            color:#fff;
	            
	        }
	         #home-stream ul{
	        	display:inline;
	        
	        }
	        #home-stream ul li{
	        	display:block;
	        float:left;
	      
	        margin-top:3px;
	        width:200px;
	        }
 #home-stream ul li:hover{
	        	
	        background-color:#ccc;
	      
	        }       
		 #home-stream ul li a{
			        	cursor:pointer;
			          width:200px;
	       float:left;
			        }
		  
	         #home-stream ul li a div{
	          margin-top:3px;
	        }
      .selected{
	          background-color:#aaa;
	        float:left;
	        }
	     #tab-stream ul{
	        	display:inline;
	        
	        }
	        #tab-stream ul li{
	        	display:block;
	        float:left;
	      
	        }  
	        #option ul,.option ul{
			display:inline;
		
		}
		#option,.option{
		width:150px;
		position:absolute;
		background-color:#ccc;
		 -moz-box-shadow: 0px 0px 5px 5px rgba(152,164,238,1.3);
	        -webkit-box-shadow: 0px 0px 5px 5px rgba(152,164,238,1.3);
	        -ms-box-shadow: 0px 0px 5px 5px rgba(152,164,238,1.3);
	        box-shadow: 1px 1px 2px 2px rgba(152,164,238,1.3);
		}
		#option ul li,.option ul li{
			display:block;
		width:144px;
		
			padding:2px;
	
		}
		#option ul li:hover,.option ul li:hover{
			display:block;
		background-color:#eee;
		cursor:pointer;
		}
		
		#option ul li a,.option ul li a{
			width:200px;
			padding:2px;
		color:#000;
			
		}
		   
	        
	     </style>
	     <script type="text/javascript">
	     
	     $('#create-lists').live('click',function(){
	     		 $a='<div id="list-create"><div style="width:200px; display:block; position:relative; margin-left:2px; float:left; padding:5px; background-color:#ccc; border:solid 1px"><input id="list-name" style="width:200px; outline:none; height:25px"placeholder="create your list"/></div><a onclick="$(\'#list-create\').remove()" style="float:left;cursor:pointer; font-weight:bold">cancel</a><a style="float:right; cursor:pointer; cursor:pointer;font-weight:bold"onclick="createlists()">create</a></div>';   
                  
                  $('#create-lists-div').html($a);
                  
                  });
                   $('#add-lists').live('click',function(){
                   $('#add-lists').toggle(function() {
	     		 $('#add-list-create').css('display','block');
                   $('#add-lists div').html('cancel');
                   },function(){
                   $('#add-lists div').html('+');
                  $('#add-list-create').css('display','none');
          });
                  
                 
                  });
                  
                  function createlists(){
                  var name=$('#list-name').val();
                  $.ajax({
	    		    url:'http://www.freniz.com/list/create?name='+name,
	    		    cache:false,
	    		    dataType:"json",
	    		    success:function(json){
	    		    	 if(json.status=='success'){
	    		    	  $a='<li><a><span><div style="width:20px;  float:left; height:20px;"><img src="'+json.picture+'" height="20" width="20"/></div><div style="width:175px; margin-left:2px;  float:left; height:20px; ">'+json.name+'</div></span></a></li>';
	    		    	 $('#lists-items').after($a);
	    		     }
	    		     $('#list-create').remove();
	    		    }
	 		    } );
                  }
			
	     </script>
	     
	    </head>
	    <body>
 <img id="loading" src="images/prettyGallery/loading-gif-animation.gif" style="position:absolute; display: none; margin-left: 45%" height="32" width="32"></img>
    <div class="headerdiv">
<div id="freniz-logo" style="width:220px; float:left; height:60px; ">
    <a style="text-decoration:none; cursor: pointer; "href="#"><img src="http://images.freniz.com/freniz.png"/></a>
</div>
<div id="smile-mood-change" style="width:40px; float:left; height:60px; ">
<?php if(isset($session['userid']) && $session['type']!='none' && $session['type']!='leaf'){ ?>
   <div style="width:40px; margin-top: 10px; float:left; height:40px; "><img id="top-smiley" style="cursor: pointer;marin-top:10px" src="http://images.freniz.com/mood/32/<?php $smood=explode(',', $session['mood']); echo $smood[0];?>" width="40" height="40"/></div>
<?php } ?>
</div>
<div id="top-menu-items" style=" float:left; height:60px; ">
<div style="height:30px; margin-top: 15px; margin-left: 30px;  float:left; ">
    <?php if(isset($session['userid']) && $session['type']=='user'){ ?>
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/">Stream</a></li>
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/<?php echo $session['userid']; ?>">Bio</a></li>
	<li class="link-bord" id="top-underline"><a id="mes-a" href="http://www.freniz.com/messages">Message</a></li>
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/blog/<?php echo $session['userid']; ?>">Blog</a></li>
	
	<li class="link-bord">
		<a id="alert-a" href="#">Alert</a>
				<ul style=" margin-top: -5px;">
					<li><a id="noti-a" href="http://www.freniz.com/notification">Notifications</a></li>
					<li><a id="revi-a" href="http://www.freniz.com/review/reviews">Reviews</a></li>
				</ul>				
	</li>
	<li class="link-bord">
		<a href="#">Apps</a>	
		<ul style=" margin-top: -5px;">
					 <li ><a href="http://www.freniz.com/forum">Forum</a></li>
                    <li><a href="http://www.freniz.com/diary">Diary</a></li>
					<li><a href="http://www.freniz.com/slambook">Slam book</a></li>
				</ul>		
	</li>
	
</ul>
<?php }else{ ?>
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/<?php echo $session['userid']; ?>">Home</a></li>
<ul>

<?php } ?>
</div>

</div>
<div style=" width: 250px; margin-right: 10px; float:right; height:60px; ">
<?php if($session['userid']){ ?> 
<div id="accout-name-settings" style=" float:right; font-weight: bold; color: #fff; height:40px;">
   
 <nav>
           <ul>
		<li id="settings">
			<a id="acount-trigger-setting" href="javascript:void(0)" title="<?php echo $session['username']; ?>" class="active">
				<?php 
				$name = $session['username'];
                 if(strlen($name) > 24 )
                 {
                 echo substr($name, 0, 26).'...' ;
                                 }
               else {
                   echo $name;
               } ?> <span id="logspan">&#x25BC;</span>
			</a>
			<div id="acount-content-setting" >
                            <ul>
                                <label style="color:#999; font-size: 18px; font-weight: bold">Freniz Account</label>
                                <?php 
                                $val=$session['adminpages_details'];
                                unset($val[$session['userid']]);
                                foreach ($val as $value){
                                	?>
                            		<li title="<?php echo $value['username']; ?>" onclick="switchuser('<?php echo $value['userid'];?>')"  ><div style="border-bottom:solid 1px #ccc; padding:3px; height:16px"><label  style="color:#999; height:16px;float:left;font-weight: bold"><img style="width:16px; height:16px; float:left" src="http://images.freniz.com/32/32_<?php echo $value['propic_url'];?>"/><a title="<?php echo $value['username']; ?>" style="font-size:10px;padding-left:4px;"><?php $leafname = $value['username'];
                 if(strlen($leafname) > 15 )
                 {
                 echo substr($leafname, 0, 15).'...' ;
                                 }
               else {
                   echo $leafname; } ?></a></label></div></li>
                                 	<?php } 
                                 	if($session['type']!='none' && $session['type']!='leaf'){
                                 	?>
                                 	 <li ><a href="http://www.freniz.com/index/personalinfo?log_aug=finis">Account Settings</a></li>
                                 <li><a href="http://www.freniz.com/index/privacysettings">Privacy Setting</a> </li>
                                <?php }elseif($session['type']=='leaf'){ ?>
                                   <li><a href="http://www.freniz.com/leafedit/<?php echo $session['userid']; ?>#privacyinfo">Privacy Setting</a> </li>
                                <?php } ?>
                                 <li><a href="#">Help</a></li>
                                 <li><a href="http://www.freniz.com/index/logout">Take Out</a> </li>
                            </ul>
			</div>                     
		</li>
                
            </ul>
        </nav>

    
 
</div>
 <?php }else {?>
      <div style="width:250px; height: 40px; float:right">
             <a style=" padding:3px 10px; float:right" href="http://www.freniz.com/loginattempt" id="leaf-vote">Login</a>
          </div>
    <?php } ?>
 
<div id="search-option-items" style="width:200px; margin-top: -10px;margin-right:50px;  float:right; height:20px; ">
    <input class="search-box" id="searchusers"  type="text" placeholder="search" onfocusout="searchitemsout(this)" onfocus="searchitemsin(this)" style="width:250px; height:30px" ><span id="searchusers-load" style="margin-top:-24px; margin-left: 215px; color: #ffffff; display: none; position: absolute;"><img src="images/blackloading.gif" height="16" width="16"/></span></input>
    <span style="color:#ccc; cursor: pointer; font-size: 12px; float: right; margin-top: -24px; margin-right:-45px">&#x25BC;</span>
</div>
</div>


</div>          
	        <div style="width:1000px; margin-left: auto; margin-right: auto;">
	        <div id="maincontainer">
	        	 
	           <!-- main div close --> 
	              
	                  <div id="home-stream" style="width:200px; border-right:solid 1px;float: left; ">
	             <div style="width:190px; padding:5px; height:60px; ">
	             <div style="width:50px; height:50px; float:left; border:solid 1px">
	             <img src="http://images.freniz.com/50/50_<?php echo $session['propic_url']; ?>" />
	             </div>
	             <div style="width:130px; margin-left:3px; height:50px; float:left; ">
	             <label><?php echo $session['username']; ?></label>
	             </div>
	             
	             
	             </div>
	             
	             <ul>
	             <li id="lists-items"><a href="http://www.freniz.com"><span ><div style="width:20px;  float:left; height:20px;"><img src="j.png" height="20" width="20"/></div><div style="width:175px; margin-left:2px;  float:left; height:20px; ">Stream</div></span></a></li>
	             
	              <?php foreach($lists as $list){
	               ?>
	             <li><a href="http://www.freniz.com/list/display?id=<?php echo $list['id'];  ?>"><span class="<?php if($_REQUEST['id']==$list['id']) echo"selected"; ?>"><div style="width:20px;  float:left; height:20px;"><img src="<?php echo $list['picture']; ?>" height="20" width="20"/></div><div style="width:175px; margin-left:2px;  float:left; height:20px; "><?php echo $list['name']; ?></div></span></a></li>
	            <?php } ?>     
	              <li><a id="create-lists" style="width:200px; text-align:center; font-weight:bold">Add list +</a></li>
	                </ul>
	             <div id="create-lists-div">
	             
	             </div>
	             </div>
	         
	               <div id="tab-stream"  style="width:700px; padding:2px; border-bottom:solid 1px; height:50px; float: left; ">
	              <ul>
	              <?php foreach($this->result['userpro'] as $val) { ?>
	             <li><a title="<?php echo $val['username'];  ?>" href="http://www.freniz.com/<?php echo $val['userid'];  ?>"><span><div style="width:50px;  float:left; height:50px;"><img src="http://images.freniz.com/50/50_<?php echo $val['propic_url'];  ?>" height="50" width="50"/></div></span></a></li>
	            <?php } ?>
	             <li><a id="add-lists" style="cursor:pointer" ><div style="padding:15px; text-align:center; font-weight:bold">+</div></a></li>
	            
	                </ul>
	         <div id="add-lists-div" style="width:220px; float:left ">
	             <div id="add-list-create" style="display:none"><div style="width:200px; display:block; position:relative; margin-left:-50px; margin-top:30px; float:left; padding:5px; background-color:#ccc; border:solid 1px"><input id="friends-list" style="width:200px; outline:none; height:25px"placeholder="Add ur Friends"/></div></div>
	             </div>
	          </div>
	         
	            <div style="width:500px; padding:3px; float: left; ">
	            
	            
	            <!-- text feild -->
	            
	           <!-- text feild close --> 
	     		<?php $users=implode(',',$this->result['listitems']); 
	     		
	     		?>
	     <script type="text/javascript">
					getstreams('','<?php if(empty($users)) echo 'NULL'; else echo $users; ?>');
				setTimeout(function(){loadcomments();},2000);
	         </script>
	 <div id="streams" style="width: 500px; margin-top:5px; float: left;">
	 
             </div>
             </div>
             <div style="width:200px;  height:100px; float: left; ">
             <a id="settings-leaf" style="float:right;text-decoration:none; color:#444" href="javascript:void(0)">settings</a>
             <div id="settings-leaf-div">
             </div>
            
	            </div>
	            <!-- blog close -->
	            <div id="footer" style="width: 100%; height: 100px; float: left; ">
    
    
    
</div>
 
	            </div>
	           </div> 
	         
	   
        <div id="light" class="white_content"></div>
    <div id="fade" onClick="document.getElementById('light').style.display='none';  document.getElementById('fade').style.display='none'" class="black_overlay">
        </div>
	<!-- 
	  <div id="remove-items" style="width:130px; display:none; background-color:#eee;float:left; ">
<ul>
<li class="delete" ><a href="javascript:void(0)">delete</a></li>
<li><a href="javascript:void(0)">Settings</a></li>
<li><a  href="javascript:void(0)">Report</a></li>
</ul>
</div> 
	 -->  
	 
	      <!-- <div style="border: solid 1px; width:100%; height:270px; background-image:url(images/banner.png)"></div>  --> 
	 <div id="musictab">

 <div class="foot-tab">
     <ul>
 <li><a href="#">About</a></li>
         <li><a href="http://www.freniz.com/search">Search</a></li>
         <li><a href="#">Terms</a></li>
         <li><a href="#">Privacy</a></li>
         <li><a href="#">Help</a></li>
         <li><a href="http://www.freniz.com/createleaf">Create a leaf</a></li>
          <li><a href="http://www.freniz.com/developers">Developers</a></li>
         <li><a href="http://www.freniz.com/hireus">Hire Us</a></li>
     </ul>
 </div> 
       
</div>
 <div id="hover-data"></div>
 <script type="text/javascript">


					var options_xmlsearch = function(type,appendto){
						     if(!appendto)
					        appendto='body'; 
					     var options={
					                script:"http://www.freniz.com/search?type="+type+"&",
							varname:"key",
					                type:type,
					                appendto:appendto,
					                callback:function(suggestion,fld){
					                
				  $.ajax({
			  		    url:'http://www.freniz.com/list/addusers?users='+suggestion.id+'&id=<?php echo $_REQUEST['id'];?>',
			  		    cache:false,
			  		    dataType:"json",
			  		    success:function(json){
			  		    if(json.status=='success'){
			  		          $('#add-lists div').html('+');
			  		    	  $('#add-list-create').css('display','none');
			  		    	   $a='<li><a title="'+suggestion.name+'" href="http://www.freniz.com/'+suggestion.id+'"><span><div style="width:50px;  float:left; height:50px;"><img src="http://images.freniz.com/50/50_'+suggestion.pic+'" height="50" width="50"/></div></span></a></li>';
	           					$('#tab-stream ul').prepend($a);
			  		    	  }
			  		    }
					    } );
	    								
					                       
					                       }
					                
					            };
					            return options;
						}
          
          var options_xmlsearch = new AutoSuggest('friends-list', options_xmlsearch('all')); 
        
        
</script>
	    </body>  
	    
	    
	    
	    
	</html>
<?php } ?>