<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$session=(array)$this->mydetails;
$ud=$this->userDetails; 
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Messages</title>
<script type="text/javascript" src="http://js.freniz.com/jquery-latest.js"></script>
<script src="http://js.freniz.com/ajax.js" type="text/javascript"></script>
	        <link rel="stylesheet" href="http://css.freniz.com/default.css" type="text/css" media="screen" charset="utf-8" />
<link rel="stylesheet" href="http://css.freniz.com/autosuggest_inquisitor.css" type="text/css" media="screen" charset="utf-8" />
<script type="text/javascript" src="http://js.freniz.com/leaf.js"></script>
<script src="http://js.freniz.com/jquery.timeago.js" type="text/javascript"></script>
	<script type="text/javascript" src="http://js.freniz.com/bsn.AutoSuggest_c_2.0.js"></script>
   
<style>
body{
   font-size: 99%;
   background-color: #fff;
   color: #000;
   font-family: arial, helvetica, geneva, sans-serif;
   margin-left:1px;
   margin-top:0px;
}


#side-menu ul{
		display:inline;
		width:150px;
		margin-top:-50px;
	}
	#side-menu ul li{
		display:block;
		background-color:#FFF;
		padding:20px;
		
		
	}
	#side-menu ul li a{
		text-decoration:none;
		color:black;
		position:absolute;
		padding:5px;
	}
	#side-menu ul li a:hover{
		background-color:#A4A4A4;
		width:150px;
		display:block;
		color:#FFF;
		 -moz-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  -webkit-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);	
		padding:5px;
		
		
	}
	.show-selected{
		background-color:#A4A4A4;
		width:150px;
		display:block;
		color:#FFF;
		 -moz-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  -webkit-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		padding:5px;
	}
   #left-mess{
            	padding:10px;
            	 border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
             -moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        -webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
	        -ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);
            background-color:#E0F8E0;
            margin-left:10px;
             max-width:350px;
            float:left;
            }
            #send-reply{
            	 -moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        -webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
	        -ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);
            }
 #right-mess{
 	padding:10px;
            	 border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
             -moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        -webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
	        -ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);
            background-color:#A9F5BC;
            float:right;
            margin-right:10px;
            max-width:350px
            }
            #mess-user,#mess-inner{
            	padding:5px;
            	 border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
             -moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        -webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
	        -ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);
            }
 #img-user{
            	 border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
             -moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        -webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
	        -ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
	        box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);
            }
            #mess-container{
            	padding:3px;
            -moz-box-shadow: 6px 6px 3px 0px rgba(68, 68, 68, 0.2);
	        -webkit-box-shadow: 6px 6px 3px 0px rgba(68, 68, 68, 0.2);
	        -ms-box-shadow:6px 6px 3px 0px rgba(68, 68, 68, 0.2);
	        box-shadow: 6px 6px 3px 0px rgba(68, 68, 68, 0.2);
	       
            }
            #message-inbox ul{
            	display:inline;
            }
#message-inbox ul li{
            display:inline;	
            }
#message-inbox ul li a{
            text-decoration:none;
            color:#ccc;
            }

            
</style>
<script type="text/javascript">

$('.mess-conv').live('click',function(){
	var a='<div id="mess-inner" style="width: 400px; position:absolute; margin-left:-250px; margin-top:40px; background-color:#eee; padding:10px; height:190px;  "><div style="width:350px; float :left;padding:10px;"><input id="search-friends" type="text"placeholder="Enter the name"style="width:350px; height:30px;"/><input type="hidden" value="" id="search-friends-hidden"/></div><div style="width:350px;float :left; padding:10px; height:70px;"><textarea id="mess-cont" style="width:350px; height:70px;"placeholder="write something..."></textarea></div><span style="float:right; margin-top:10px;"class="leaf-vote"id="leaf-vote">send</span><span style="float:right; margin-top:10px;"onclick="$(\'#mess-inner\').remove();"id="leaf-vote">cancel</span></div>';
		$('#mess-conv').append(a);
		var as_xmlsearch = new AutoSuggest('search-friends', options_xmlsearch('friends'));
});

</script>
</head>

<body>
 <img id="loading" src="images/prettyGallery/loading-gif-animation.gif" style="position:absolute; display: none; margin-left: 45%" height="32" width="32"></img>
    <div class="headerdiv">
<div id="freniz-logo" style="width:220px; float:left; height:60px; ">
    <a style="text-decoration:none; cursor: pointer; "href="#"><img src="http://images.freniz.com/freniz.png"/></a>
</div>
<div id="smile-mood-change" style="width:40px; float:left; height:60px; ">
<?php if(isset($session['userid']) && $session['type']!='none' && $session['type']!='leaf'){ ?>
   <div style="width:40px; margin-top: 10px; float:left; height:40px; "><img id="top-smiley" style="cursor: pointer;marin-top:10px" src="http://images.freniz.com/mood/32/<?php $smood=explode(',', $session['mood']); echo $smood[0];?>" width="40" height="40"/></div>
<?php } ?>
</div>
<div id="top-menu-items" style=" float:left; height:60px; ">
<div style="height:30px; margin-top: 15px; margin-left: 30px;  float:left; ">
    <?php if(isset($session['userid']) && $session['type']=='user'){ ?>
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/">Stream</a></li>
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/<?php echo $session['userid']; ?>">Bio</a></li>
	<li class="link-bord" id="top-underline"><a id="mes-a" href="http://www.freniz.com/messages">Message</a></li>
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/blog/<?php echo $session['userid']; ?>">Blog</a></li>
	
	<li class="link-bord">
		<a id="alert-a" href="#">Alert</a>
				<ul style=" margin-top: -5px;">
					<li><a id="noti-a" href="http://www.freniz.com/notification">Notifications</a></li>
					<li><a id="revi-a" href="http://www.freniz.com/review/reviews">Reviews</a></li>
				</ul>				
	</li>
	<li class="link-bord">
		<a href="#">Apps</a>	
		<ul style=" margin-top: -5px;">
					 <li ><a href="http://www.freniz.com/forum">Forum</a></li>
                    <li><a href="http://www.freniz.com/diary">Diary</a></li>
					<li><a href="http://www.freniz.com/slambook">Slam book</a></li>
				</ul>		
	</li>
	
</ul>
<?php }else{ ?>
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/<?php echo $session['userid']; ?>">Home</a></li>
<ul>

<?php } ?>
</div>

</div>
<div style=" width: 250px; margin-right: 10px; float:right; height:60px; ">
<?php if($session['userid']){ ?> 
<div id="accout-name-settings" style=" float:right; font-weight: bold; color: #fff; height:40px;">
   
 <nav>
           <ul>
		<li id="settings">
			<a id="acount-trigger-setting" href="javascript:void(0)" title="<?php echo $session['username']; ?>" class="active">
				<?php 
				$name = $session['username'];
                 if(strlen($name) > 24 )
                 {
                 echo substr($name, 0, 26).'...' ;
                                 }
               else {
                   echo $name;
               } ?> <span id="logspan">&#x25BC;</span>
			</a>
			<div id="acount-content-setting" >
                            <ul>
                                <label style="color:#999; font-size: 18px; font-weight: bold">Freniz Account</label>
                                <?php 
                                $val=$session['adminpages_details'];
                                unset($val[$session['userid']]);
                                foreach ($val as $value){
                                	?>
                            		<li title="<?php echo $value['username']; ?>" onclick="switchuser('<?php echo $value['userid'];?>')"  ><div style="border-bottom:solid 1px #ccc; padding:3px; height:16px"><label  style="color:#999; height:16px;float:left;font-weight: bold"><img style="width:16px; height:16px; float:left" src="http://images.freniz.com/32/32_<?php echo $value['propic_url'];?>"/><a title="<?php echo $value['username']; ?>" style="font-size:10px;padding-left:4px;"><?php $leafname = $value['username'];
                 if(strlen($leafname) > 15 )
                 {
                 echo substr($leafname, 0, 15).'...' ;
                                 }
               else {
                   echo $leafname; } ?></a></label></div></li>
                                 	<?php } 
                                 	if($session['type']!='none' && $session['type']!='leaf'){
                                 	?>
                                 	 <li ><a href="http://www.freniz.com/index/personalinfo?log_aug=finis">Account Settings</a></li>
                                 <li><a href="http://www.freniz.com/index/privacysettings">Privacy Setting</a> </li>
                                <?php }elseif($session['type']=='leaf'){ ?>
                                   <li><a href="http://www.freniz.com/leafedit/<?php echo $session['userid']; ?>#privacyinfo">Privacy Setting</a> </li>
                                <?php } ?>
                                 <li><a href="#">Help</a></li>
                                 <li><a href="http://www.freniz.com/index/logout">Take Out</a> </li>
                            </ul>
			</div>                     
		</li>
                
            </ul>
        </nav>

    
 
</div>
 <?php }else {?>
      <div style="width:250px; height: 40px; float:right">
             <a style=" padding:3px 10px; float:right" href="http://www.freniz.com/loginattempt" id="leaf-vote">Login</a>
          </div>
    <?php } ?>
 
<div id="search-option-items" style="width:200px; margin-top: -10px;margin-right:50px;  float:right; height:20px; ">
    <input class="search-box" id="searchusers"  type="text" placeholder="search" onfocusout="searchitemsout(this)" onfocus="searchitemsin(this)" style="width:250px; height:30px" ><span id="searchusers-load" style="margin-top:-24px; margin-left: 215px; color: #ffffff; display: none; position: absolute;"><img src="images/blackloading.gif" height="16" width="16"/></span></input>
    <span style="color:#ccc; cursor: pointer; font-size: 12px; float: right; margin-top: -24px; margin-right:-45px">&#x25BC;</span>
</div>
</div>


</div>  
<div id='maincontainer' style="width:1000px; margin-left: auto; margin-right: auto; ">
       <div id="side-menu" style="width:200px; margin-top:5px; border-right:solid 1px; float:left; ">
<ul>
<li><a class="show-selected" href="http://www.freniz.com/messages">Inbox</a></li>
<li><a  href="http://www.freniz.com/messages/sentmessages">Sent</a></li>
</ul>
</div> 


    <div id="message-inbox" style="width:550px; padding:5px; float:left;  ">
    <ul>
    <li><a href="http://www.freniz.com/messages">Inbox</a></li>
    <?php if(!empty($ud)){?>
    <li>></li>
    <li><a href="http://www.freniz.com/<?php echo $ud['userid'];?>"><?php echo $ud['username'];?></a></li>
   <?php }?> </ul>
    	<div id="mess-container"style="width:550px; float:left;height:50px; ">
	<div style="width:245px; float:left;height:50px; ">
	<div style="width:50px; float:left;height:50px; ">
	<img id="img-user" src="http://images.freniz.com/50/50_<?php echo $session['propic_url'];?>" height="50" width="50" />
	</div>
	<div  style="width:180px; padding:5px;  float:left;height:40px; ">
	<label id="mess-user" style="background-color:#E0F8E0;"><?php echo $session['username'];?></label>
	</div>
	</div>
	<?php if(!empty($ud)){?>
	<div style="width:245px; margin-left:60px; float:left;height:50px; ">
	<div style="width:50px; float:right;height:50px;">
	<img id="img-user" src="http://images.freniz.com/50/50_<?php echo $ud['propic_url'];?>" height="50" width="50" />
	</div>
	<div  style="width:180px;  padding:5px; float:right;height:40px; ">
	<label id="mess-user" style="float:right;background-color:#A9F5BC;"><?php echo $ud['username'];?> </label>
	</div>
	</div>
	<?php } ?>
	</div>
	
        <script type="text/javascript"> <?php if(empty($ud)){
            echo "getmessages()";
        }else{
			echo "getusermessages('".$ud['userid']."')";

}
		
        ?>
            </script>
       <div  id="primarydiv" style="width:550px; max-height:400px; overflow:auto; float:left;"></div>
        <?php if(!empty($ud)){?>
         <div id="send-reply"style="width:500px; height: 30px; background-color:#eee; padding:20px; float:left">
         <input id="send-text"onkeyup="sendmessageuser('<?php echo $ud['userid'];?>',event)"placeholder="reply..."style="width:500px; resize: none;  height:30px;"></input>
         <label style="color:#444;">Press enter to send</label>
         </div>   
          <?php }?>  
    </div>
  <div style="width:230px; height:300px; border-left:solid 1px; float:right">
  <div  style="width:220px; height:50px; padding:3px;  float:right">
            <span class="mess-conv" id="leaf-vote" style="float:left; margin-left:0px">New conversation</span>
	    <div id="mess-conv"></div>      
  </div>
  </div>
    
</div>

<script type="text/javascript">

				
getcount();	
								
					function miniprofile(data,element){
							var position=$(element).offset();
							getminiprofile(data,position.top,position.left);
						}


					var options_xmlsearch = function(type,appendto){
					     if(!appendto)
					        appendto='body'; 
					     var options={
					                script:"http://www.freniz.com/search?type="+type+"&",
							varname:"key",
					                type:type,
					                appendto:appendto,
					                callback:function(suggestion,fld){
												window.location.href="http://www.freniz.com/"+suggestion.id;
					                       }
					                
					            };
					            return options;
						}
           var options_xmlsearch = new AutoSuggest('searchusers', options_xmlsearch('all'));
           var options_xmlsearch = function(type,appendto){
       	 	if(!appendto)
       	        appendto='body'; 
       	        var options={
       	                script:"http://www.freniz.com/search?type="+type+"&",
       					varname:"key",
       	                type:type,
       	           		appendto:appendto,
       	                callback:function(suggestion){
       	                 $('#search-friends-hidden').val(suggestion.id);
       	                 $('#search-friends').val(suggestion.name);
       	                 $('.leaf-vote').click(function(){sendmessageuser(suggestion.id);});
       						   }
       	                
       	           	 };
       	          	  return options;
       				}
        
        
</script>
 <div id="musictab">
<div class="foot-tab" id="foot-tab">
     <ul>
 <li><a href="#">About</a></li>
         <li><a href="http://www.freniz.com/search">Search</a></li>
         <li><a href="#">Terms</a></li>
         <li><a href="#">Privacy</a></li>
         <li><a href="#">Help</a></li>
         <li><a href="http://www.freniz.com/createleaf">Create a leaf</a></li>
          <li><a href="http://www.freniz.com/developers">Developers</a></li>
         <li><a href="http://www.freniz.com/hireus">Hire Us</a></li>
     </ul>
     
 </div> 
       
</div>
</body>
</html>