<?php
header("Cache-Control: no-cache, must-revalidate" );
header("Pragma: no-cache" );
header("Content-Type: text/xml; charset=utf-8");
$session=(array)$this->mydetails;
$results=$this->results['results'];
?>
<videos>
	<loadmore><?php if($this->results['loadmore']) echo 'yes'; else echo 'no'; ?></loadmore>
		<?php foreach ($results as $row){?>
		<video>
		<videoid><?php echo $row['videoid'];?></videoid>
		<title><?php echo $row['title'];?></title>
		<embeddcode><?php echo htmlspecialchars($row['embeddcode']);?></embeddcode>
		<vote_count> <?php $votes=unserialize($row['vote']); echo count($votes); ?> </vote_count>
		<votecontains><?php if(in_array($session['userid'], $votes)){
                            echo "yes";
                     }
                        else 
                            echo "no";
                            ?></votecontains>
		<date><?php echo $row['date'];?></date>
		<suserid><?php echo $row['suserid'];?></suserid>
		<ruserid><?php echo $row['ruserid'];?></ruserid>
		<accepted><?php echo $row['accepted'];?></accepted>
		<pt><?php echo $row['pt'];?></pt>
		<specificlist><?php echo $row['specificlist'];?></specificlist>
		<hiddenlist><?php echo $row['hiddenlist'];?></hiddenlist>
		<commentcount><?php echo $row['commentcount'];?></commentcount>
		<notifyusers><?php echo $row['notifyusers'];?></notifyusers>
		<susername><?php echo $row['susername'];?></susername>
		<suser_url><?php echo $row['suser_url'];?></suser_url>
		<spropic><?php echo $row['spropic'];?></spropic>
		<spropic_url><?php echo $row['spropic_url'];?></spropic_url>
		<sfriendlist><?php echo $row['sfriendlist'];?></sfriendlist>
		<rusername><?php echo $row['rusername'];?></rusername>
		<ruser_url><?php echo $row['ruser_url'];?></ruser_url>
		<rpropic><?php echo $row['rpropic'];?></rpropic>
		<rpropic_url><?php echo $row['rpropic_url'];?></rpropic_url>
		<rfriendlist><?php echo $row['rfriendlist'];?></rfriendlist>
		</video>
		<?php }?>
		</videos>