<?php

	$ud=$this->bodycontent;
	$session=(array)$this->mydetails;
	

?>

	<html>

	    <head>
	     <script type="text/javascript" src="http://js.freniz.com/jquery-latest.js"></script> 
	         <script type="text/javascript" src="http://js.freniz.com/ajax.js"></script> 
	       <link rel="stylesheet" href="http://css.freniz.com/autosuggest_inquisitor.css" type="text/css" media="screen" charset="utf-8" />
	       <script type="text/javascript" src="http://js.freniz.com/bsn.AutoSuggest_c_2.0.js"></script>
	        <link rel="stylesheet" href="http://css.freniz.com/default.css" type="text/css" media="screen" charset="utf-8" />

	          <script type="text/javascript" src="http://js.freniz.com/leaf.js"></script> 
	      <script src="http://js.freniz.com/jquery.timeago.js" type="text/javascript"></script>
	     <script type='text/javascript' src="http://js.freniz.com/jquery.form.js"></script>
	     
	     <script type="text/javascript">

	     $(document).ready(function(event){
	
	    	
	     $('#blog-new').click(function(){

	           var data=$('#blog-new').offset();
	    	 $b='<div id="blog-top" style="width: 400px; position:absolute; top:'+(data.top+40)+'px; left:'+(data.left-300)+'px; background-color:#eee; padding:10px; height:220px; "><form name="blogmessage" action="http://www.freniz.com/addblog" method="post" id="blogmessage" enctype="multipart/form-data" ><div style="width:350px; float :left;padding:10px;"><input id="blg_title"  name="title" type="text"placeholder="Enter the Title"style="width:350px; height:30px;"/></div><div style="width:350px;float :left; padding:10px; height:70px;"><textarea  id="blg" name="text" style="width:350px; height:70px;"placeholder="write something..."></textarea></div><input type="file" id="blg_url" name="qqfile" value="Upload" size="40" /><input type="submit" style="float:right; margin-top:30px;"id="leaf-vote" value="Add"/><span style="float:right; margin-top:10px;margin-right:10px;"onclick="$(\'#blog-top\').remove();"id="leaf-vote">Cancel</span></form></div>';
	    	// $b='<div style="width:500px; height:200px; margin-left:20px; margin-top:20px; "><form name="blogmessage" onsubmit="createb()"><div style="width:300px; height:20px; margin-top:10px; margin-left:60px; float:left;"><input type="text" id="blg_title" size="40" /></div><div style="width:300px; height:100px; margin-top:10px; margin-left:60px; float:left;"><textarea rows="4" cols="50" id="blg" ></textarea></div><div style="width:300px; height:20px; margin-top:10px; margin-left:60px; float:left;"><input type="file" id="blg_url" value="Upload" size="40" /></div><div style="width:300px;  margin-left:40px;"><ul class="roundbuttons sendmessagewidth" style="margin-left:40px;"><li><input type="button" name="cancel" value="cancel" onClick="document.getElementById(\'light\').style.display=\'none\';   document.getElementById(\'fade\').style.display=\'none\';"  /></li><li><input type="button" name="send" value="send" onclick="createb()" /></li></ul></div></form></div>';

	    	     $('#blog-container').html($b); 

	    	     $('#blogmessage').ajaxForm({
		    	     dataType:'json',
		    	     cache:false,
		    	     success:function(json){
		    	    	 var span=document.createElement('span');
			     			$(span).css({'position':'absolute','top':'40%','left':'40%','background-color':'#fff','border':'solid 1px','padding':'25px'});
			 		    	span.id='alert-span';
			 				if(json.status=='success')
			 					span.innerHTML='Hey you sucessfully updated your blog :)';
			 				else
			 					span.innerHTML='There is an Error';
			 				$('#blog-container').append(span);
			 				setTimeout(function(){$('#alert-span').remove();},3000);	
			 				var main=document.getElementById('scribbles');
			     			  var top=document.createElement('div');
			             	  top.id='user-pic';
			             	  top.className="user-pic"+json.blogid;
			       	        top.style.width='600px';
			       				top.style.padding='10px';
			       				 top.style.cssFloat='left';  
			       				top.style.marginTop='10px';
			       				top.style.backgroundColor='#eee';
			       	          var b=document.createElement('div');
			       	             b.className='comment-tab';
			       	             b.innerHTML='<div style="width:600px; float:left; "><a id="blog-del'+json.blogid+'" class="remove"data="'+json.blogid+'" title="delete blog" style="float:right; font-size:12px; postion:absolute;  cursor:pointer; margin-right:8px;">x</a><label style="font-size:24px; padding:5px; font-weight:bold">'+json.title+'</label><br/><span style="font-size:14px; margin-left:10px; font-weight:bold; color:#ccc;"><div class="timeago" style="float:left; margin-top:3px;" title="'+json.time+'">'+json.time+'</div></span></div><div style="width:540px; padding:5px; text-align:justify; margin-left:10px; float:left;">'+json.content+'</div>';
			       	           if(json.imageurl){
			         	             var b1=document.createElement('div');
			         	         $(b1).css({'margin-left':'20px','background-color': '#c1d8a9','float':'left','margin-top':'5px'});
			         	         b1.innerHTML='<img alt="image"src="http://images.freniz.com/'+json.imageurl+'"width="400">';
			         	        b.appendChild(b1);
			         	        }
			       	         var c=document.createElement('div');
			       	              c.style.width='600px';
			       	              c.style.cssFloat='left';    
			       	           
			                     	 c.innerHTML='<a onclick="voteblog(\''+json.blogid+'\',this)"class="vote-bar"href="javascript:void(0)"style="float: right">wink( 0 )</a>';
			                     
			       	            b.appendChild(c);
			       	        
			       	        
			       	        	top.appendChild(b);
			       	        	$(main).prepend(top);
			       	        	 $(".remove").toggle(function(){
			       		    		var data=$(this).attr('data');
			       		    		var position = $("#blog-del"+data).offset();
			       		    	$('#remove-items').css({'position':'absolute','display':'block','top':+(position.top+16),'left':+(position.left-120)});
			       		    	$("#remove-items a:first").attr("onclick","deleteblog('"+data+"')");
			       		    	$("#remove-items a:last").attr("onclick","report('"+data+"')");
			       		    		
			       		    	},function(){
			       		    		$('#remove-items').css({'position':'none','display':'none'});
			       		    	});
			       	        	prettyLinks();
			       	        	$('#blog-top').remove();
		    	     }
		 				});

				
	 	              
	    	             
	    	         });
         
	     });



	     
	     </script>
	           <style>
#remove-items{
			border-radius: 10px;
-moz-border-radius: 10px;
-webkit-border-radius: 10px;
-moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
-webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
-ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);
		}
#remove-items ul{
		display:inline;
		width:100px;
            background-color:#eee;
	}
	#remove-items ul li{
		display:block;
		background-color:#FFF;
		padding:10px;
	background-color:#eee;
		
		
	}
 #alert-span{
         	    border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
             -moz-box-shadow: 5px 5px 10px 10px rgba(68,68,68,1.0);
	        -webkit-box-shadow: 2px 2px 10px 10px rgba(68,68,68,1.0);
	        -ms-box-shadow: 2px 2px 10px 10px rgba(68,68,68,1.0);
	        box-shadow: 2px 2px 10px 10px rgba(68,68,68,1.0);
         }
	#remove-items ul li a{
		text-decoration:none;
		color:black;
		position:absolute;
		padding:2px;
	}
	#remove-items ul li a:hover{
		background-color:#A4A4A4;
		width:100px;
		display:block;
		color:#FFF;
		 -moz-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  -webkit-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);	
		padding:2px;
		
		
	}
	#blog-top{
		 -moz-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
        -webkit-box-shadow: 0px 0px 5px 5px rgba(68, 68, 68, 0.6);
        -ms-box-shadow: 0px 0px 5px 5px rgba(68,68,68,0.6);
        box-shadow: 1px 1px 2px 2px rgba(68, 68, 68, 0.6);
	}
	     </style>

	    </head>

	    <body>

	   <img id="loading" src="images/prettyGallery/loading-gif-animation.gif" style="position:absolute; display: none; margin-left: 45%" height="32" width="32"></img>
    <div class="headerdiv">
<div id="freniz-logo" style="width:220px; float:left; height:60px; ">
    <a style="text-decoration:none; cursor: pointer; "href="#"><img src="http://images.freniz.com/freniz.png"/></a>
</div>
<div id="smile-mood-change" style="width:40px; float:left; height:60px; ">
<?php if(isset($session['userid']) && $session['type']!='none' && $session['type']!='leaf'){ ?>
   <div style="width:40px; margin-top: 10px; float:left; height:40px; "><img id="top-smiley" style="cursor: pointer;marin-top:10px" src="http://images.freniz.com/mood/32/<?php $smood=explode(',', $session['mood']); echo $smood[0];?>" width="40" height="40"/></div>
<?php } ?>
</div>
<div id="top-menu-items" style=" float:left; height:60px; ">
<div style="height:30px; margin-top: 15px; margin-left: 30px;  float:left; ">
    <?php if(isset($session['userid']) && $session['type']=='user'){ ?>
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/">Stream</a></li>
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/<?php echo $session['userid']; ?>">Bio</a></li>
	<li class="link-bord" id="top-underline"><a id="mes-a" href="http://www.freniz.com/messages">Message</a></li>
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/blog/<?php echo $session['userid']; ?>">Blog</a></li>
	
	<li class="link-bord">
		<a id="alert-a" href="#">Alert</a>
				<ul style=" margin-top: -5px;">
					<li><a id="noti-a" href="http://www.freniz.com/notification">Notifications</a></li>
					<li><a id="revi-a" href="http://www.freniz.com/review/reviews">Reviews</a></li>
				</ul>				
	</li>
	<li class="link-bord">
		<a href="#">Apps</a>	
		<ul style=" margin-top: -5px;">
					 <li ><a href="http://www.freniz.com/forum">Forum</a></li>
                    <li><a href="http://www.freniz.com/diary">Diary</a></li>
					<li><a href="http://www.freniz.com/slambook">Slam book</a></li>
				</ul>		
	</li>
	
</ul>
<?php }else{ ?>
<ul id="top-menu">
	<li class="link-bord" id="top-underline"><a href="http://www.freniz.com/<?php echo $session['userid']; ?>">Home</a></li>
<ul>

<?php } ?>
</div>

</div>
<div style=" width: 250px; margin-right: 10px; float:right; height:60px; ">
<?php if($session['userid']){ ?> 
<div id="accout-name-settings" style=" float:right; font-weight: bold; color: #fff; height:40px;">
   
 <nav>
           <ul>
		<li id="settings">
			<a id="acount-trigger-setting" href="javascript:void(0)" title="<?php echo $session['username']; ?>" class="active">
				<?php 
				$name = $session['username'];
                 if(strlen($name) > 24 )
                 {
                 echo substr($name, 0, 26).'...' ;
                                 }
               else {
                   echo $name;
               } ?> <span id="logspan">&#x25BC;</span>
			</a>
			<div id="acount-content-setting" >
                            <ul>
                                <label style="color:#999; font-size: 18px; font-weight: bold">Freniz Account</label>
                                <?php 
                                $val=$session['adminpages_details'];
                                unset($val[$session['userid']]);
                                foreach ($val as $value){
                                	?>
                            		<li title="<?php echo $value['username']; ?>" onclick="switchuser('<?php echo $value['userid'];?>')"  ><div style="border-bottom:solid 1px #ccc; padding:3px; height:16px"><label  style="color:#999; height:16px;float:left;font-weight: bold"><img style="width:16px; height:16px; float:left" src="http://images.freniz.com/32/32_<?php echo $value['propic_url'];?>"/><a title="<?php echo $value['username']; ?>" style="font-size:10px;padding-left:4px;"><?php $leafname = $value['username'];
                 if(strlen($leafname) > 15 )
                 {
                 echo substr($leafname, 0, 15).'...' ;
                                 }
               else {
                   echo $leafname; } ?></a></label></div></li>
                                 	<?php } 
                                 	if($session['type']!='none' && $session['type']!='leaf'){
                                 	?>
                                 	 <li ><a href="http://www.freniz.com/index/personalinfo?log_aug=finis">Account Settings</a></li>
                                 <li><a href="http://www.freniz.com/index/privacysettings">Privacy Setting</a> </li>
                                <?php }elseif($session['type']=='leaf'){ ?>
                                   <li><a href="http://www.freniz.com/leafedit/<?php echo $session['userid']; ?>#privacyinfo">Privacy Setting</a> </li>
                                <?php } ?>
                                 <li><a href="#">Help</a></li>
                                 <li><a href="http://www.freniz.com/index/logout">Take Out</a> </li>
                            </ul>
			</div>                     
		</li>
                
            </ul>
        </nav>

    
 
</div>
 <?php }else {?>
      <div style="width:250px; height: 40px; float:right">
             <a style=" padding:3px 10px; float:right" href="http://www.freniz.com/loginattempt" id="leaf-vote">Login</a>
          </div>
    <?php } ?>
 
<div id="search-option-items" style="width:200px; margin-top: -10px;margin-right:50px;  float:right; height:20px; ">
    <input class="search-box" id="searchusers"  type="text" placeholder="search" onfocusout="searchitemsout(this)" onfocus="searchitemsin(this)" style="width:250px; height:30px" ><span id="searchusers-load" style="margin-top:-24px; margin-left: 215px; color: #ffffff; display: none; position: absolute;"><img src="images/blackloading.gif" height="16" width="16"/></span></input>
    <span style="color:#ccc; cursor: pointer; font-size: 12px; float: right; margin-top: -24px; margin-right:-45px">&#x25BC;</span>
</div>
</div>


</div>      

	        <div  style="width:1000px; margin-left: auto;  margin-right: auto;">
	        <div id="maincontainer">

	            <div style="width:1000px; margin-top:-10px;float:left ">

	             <div  style="width:200px; margin: 20px; float: left;">

	                <img id="profileleafpic" src="http://images.freniz.com/200/200_<?php echo $ud['propic_url'];?>"/> 

	             </div>   

	               <div style="width:450px; font-size: 24px; font-weight: bold;  float: left; margin-top: 40px; ">

	                 <div style="border-bottom:solid 1px"><?php echo $ud['username'];?></div>

	                  

	             </div>

	                 <div style="width:450px; height: 100px; float: left;">
                 <div style="width:450px; float: left; ">
                  <div style="width:420px; height: 20px; float: left; font-size:12px; ">
                    <label>college:</label>  <?php
								 $colleges=array_reverse($ud['college']);
						$i=0;
						foreach($colleges as $college){
						      if($i<1){
						          
						          echo '<a href="http://www.freniz.com/'.$college.'">'.$ud['fav_pages'][$college]['pagename'].'</a>';
						          
						           }
						           $i++;
						      }
						?>
                  </div>  
                      <div style="width:420px; height: 20px; float: left; font-size:12px;">
                        <label>worked at:</label> <?php
								 $employers=array_reverse($ud['employer']);
						$i=0;
						foreach($employers as $employer){
						      if($i<1){
						          
						          echo '<a href="http://www.freniz.com/'.$employer.'">'.$ud['fav_pages'][$employer]['pagename'].'</a>';
						          
						           }
						           $i++;
						      }
						?>
                  </div>  
                 </div>    
                   <div style="width:400px; height: 20px; font-size: 14px; color: #444; float: left; ">
                   <label>skills:</label><?php echo $ud['skills']; ?>
                 </div> 
                     <div style="width:400px; height: 20px; font-size: 14px; color: #444; float: left; ">
                         <label>Email:</label><a style="color:#444" ><?php echo $ud['email'];?></a>
                 </div> 
                  
             </div>

	                 <div style="width:300px; height: 120px; float: right; margin-top: -50px;">

	                     

	                       <div style="width:200px; height: 50px; float: right; margin-top: 10px; ">
	                        <?php 
                        if(!in_array($session['userid'], $ud['vote'])){
                        ?>
						 <span style="padding: 6px 20px;" onclick="uservote('<?php echo $ud['userid']; ?>',this)" id="leaf-vote">Wink( <?php echo count($ud['vote']);?> )</span>
                        <?php }else{ ?>
                       <span style="padding: 6px 20px;"  onclick="userunvote('<?php echo $ud['userid']; ?>',this)" id="leaf-vote">Winked( <?php echo count($ud['vote']);?> )</span>
                        <?php }  ?>

	             </div> 

	             </div> 

	                 <div style="width:1000px; height: 50px; float: right; margin-top: -60px; border-bottom: solid 2px">

	                      

	             </div>    

	                

	            </div>

	           <!-- main div close --> 

	              

	            

	            <div  style="width:1000px;float: left;  ">
	          <?php if($ud['userid']==$session['userid']){?>
	            <div style="width:300px; height: 50px; float: right; ">
	                           <span id="blog-new" style="padding: 6px 40px;">Create New Blog</span>
	             </div> 

	          <?php }?>
	            <div style="width:700px;float: left; ">
	            
	            <label style="font-size: 24px; 	text-transform: uppercase; "><?php echo $ud['username'];?>'s Blog</label>
	            

	            <!-- text feild -->

	            

	           <!-- text feild close --> 

	         <!-- blog start -->   
	      
	        <script type="text/javascript">
	        getblogtemp('<?php echo $ud['userid'];?>');
	        </script>

	       <div id="scribbles" style="width: 700px; margin-top:5px; float: left;">
            </div> 
	         </div>
	         </div>
	            <!-- blog close -->
	            <div id="footer" style="width: 100%; height: 200px; float: left;">
    
    
    
</div>
 
	            </div>

	           </div> 
	          
	          


        <div id="blog-container" ></div>
        
<script type="text/javascript">

				
getcount();	
								
					function miniprofile(data,element){
							var position=$(element).offset();
							getminiprofile(data,position.top,position.left);
						}


					var options_xmlsearch = function(type,appendto){
					     if(!appendto)
					        appendto='body'; 
					     var options={
					                script:"http://www.freniz.com/search?type="+type+"&",
							varname:"key",
					                type:type,
					                appendto:appendto,
					                callback:function(suggestion,fld){
												window.location.href="http://www.freniz.com/"+suggestion.id;
					                       }
					                
					            };
					            return options;
						}
           var options_xmlsearch = new AutoSuggest('searchusers', options_xmlsearch('all'));
        
        
        
</script>
          <!-- <div style="border: solid 1px; width:100%; height:270px; background-image:url(images/banner.png)"></div>  --> 

	  <div id="remove-items" style="width:130px; display:none; background-color:#eee;float:left; ">
<ul>
<li class="delete" ><a href="javascript:void(0)">delete</a></li>
<li><a href="javascript:void(0)">Settings</a></li>
<li><a  href="javascript:void(0)">Report</a></li>
</ul>
</div> 
	 <div id="musictab">

 <div class="foot-tab">
     <ul>
 <li><a href="#">About</a></li>
         <li><a href="http://www.freniz.com/search">Search</a></li>
         <li><a href="#">Terms</a></li>
         <li><a href="#">Privacy</a></li>
         <li><a href="#">Help</a></li>
         <li><a href="http://www.freniz.com/createleaf">Create a leaf</a></li>
          <li><a href="http://www.freniz.com/developers">Developers</a></li>
         <li><a href="http://www.freniz.com/hireus">Hire Us</a></li>
     </ul>
     
 </div> 
       
</div>  
	  
	    </body>  

	    

	    

	    

	    

	</html>
