<?php
header("Cache-Control: no-cache, must-revalidate" );
header("Pragma: no-cache" );
header("Content-Type: text/xml; charset=utf-8");
?>
<users>
<user>
<?php foreach($this->results as $userid=>$values){?>
        <userid><?php echo $userid; ?></userid>
		<username><?php echo $values['username']; ?></username>
		<user_url><?php echo $values['user_url']; ?></user_url>
		<imageurl><?php echo $values['propic_url']; ?></imageurl>
		
</user>
<?php } ?>
</users>




