
<?php $session=(array)$this->myDetails;?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Advancedsettings</title>
<style>
.curve {
    -moz-border-radius : 25px; /* Firefox */
    -webkit-border-radius :25px; /* Safari & Chrome */
    -khtml-border-radius : 25px; /* Linux browsers */
    border-radius : 25px; /* CSS3 compatible browsers */
}
body {
    margin: 0;
    padding: 0;
    text-align: center; /* !!! */
	width:99%;
}
.centered {
    margin: 0 auto;
    text-align: left;
    width: 1000px;
	
}

.greenbutton{

background-color: #C1DF79;
background-image: -webkit-gradient(linear, left top, left bottom, from(#C1DF79), to(#C1DF79));
background-image: -webkit-linear-gradient(top, #C1DF79, #C1DF79);
background-image: -moz-linear-gradient(top, #C1DF79, #C1DF79);
background-image: -ms-linear-gradient(top, #C1DF79, #C1DF79);
background-image: -o-linear-gradient(top, #C1DF79, #C1DF79);
background-image: linear-gradient(top, #C1DF79, #C1DF79);
-moz-border-radius: 3px;
-webkit-border-radius: 3px;
border-radius: 3px;
text-shadow: 0 1px 0 rgba(0, 0, 0, .5);
-moz-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;
-webkit-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;
box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;
border: 1px solid #7E1515;
float:right;
height: 20px;
padding: ;
width: 100px;
cursor: pointer;
font: bold 12px Arial, Helvetica;
color: white;
}
.foot-tab{
width:99%;

}
.foot-tab  ul{
                    display:block;
                    margin-top: -2px;
                    text-align:left;
                   margin-left: 10px;
                   
                }
               .foot-tab ul li{
                    display:inline-block; padding: 8px;
                    font-size: 12px;
                }
                .foot-tab ul li a{
                    text-decoration: none;
                    color: #000;
                    font-weight: bold;
                    cursor: pointer;
                }
                .foot-tab ul li a:hover{
                   text-decoration: underline;
                }
                .foot-tab{
                    border-top: solid 2px #ccc;
                    margin-top: 50px;
                  float: left;
                  margin-left: 2px;
                 
                }
                .foot-tab-pos{
                    position: absolute;
                }
                
                  .show-load{
                position: absolute;
                  margin-left:500px;
                 display:none;
           width: 100px;
			height: 20px;
			background-color: #fff;
			z-index:1001;
			-moz-opacity: 0.8;
			opacity:.80;
			filter: alpha(opacity=80);
                }
nav ul {
		  margin-top:0px;
		  padding: 2px;
		  list-style: none;
		  position: relative;
		  float: left;
		  background: #eee;
		  border-bottom: 1px solid #fff;
		  -moz-border-radius: 3px;
		  -webkit-border-radius: 3px;
		  border-radius: 3px;    
		}
		
		nav li {
		  float: left;      
			   border-left:solid 1px; 
		}
     
      nav li:first-child  a{
		   
			border-left:solid 1px #eee; 
		}
		
		nav #acountmenu a {
		  display: inline-block;
		  /*display: inline;
		  *zoom: 1;  */
		  height: 25px;
		  line-height: 25px;
		  font-weight: bold;
		  padding: 0 8px;
		  text-decoration: none;
		  color: #444;
		  text-shadow: 0 1px 0 #fff; 
		}
		
		nav #acountmenu a {
		  -moz-border-radius: 0 3px 3px 0;
		  -webkit-border-radius: 0 3px 3px 0;
		  border-radius: 0 3px 3px 0;
		}
		
		
			nav #acountmenu-trigger {
		  -moz-border-radius: 3px 0 0 3px;
		  -webkit-border-radius: 3px 0 0 3px;
		  border-radius: 3px 0 0 3px;
		}
		
		nav #acountmenu a:hover {
		  background: #fff;
		}
		.active{
			background: #fff;
		}
                
</style>
     <link rel="stylesheet" href="http://css.freniz.com/login.css" type="text/css" media="screen" charset="utf-8" />
   
<script type="text/javascript" src="http://js.freniz.com/jquery-latest.js"></script>
<script type="text/javascript" src="http://js.freniz.com/ajax.js"></script>
</head>

<body>
 <div class="header-div-top" style="height:50px;">
             <a href="/"><div class="headername-font" style="width:220px; float:left; background-image: url(http://images.freniz.com/freniz.png); margin-top: -10px; height:60px; "></div></a>
     
</div>
        
<div class="centered" style="">



 <div style=" width:1000px; margin-left:auto; margin-right:auto; padding:10px; ">
 <div style="width:600px;margin-left:auto;margin-right:auto;">
<nav>
<img style="width:32px; float:left; height:32px; " src="http://images.freniz.com/32/32_<?php echo $session['propic_url'];?>"/>
	<ul>
			<li id="acountmenu" style="border-left:solid 1px #eee"><a  href="http://www.freniz.com/<?php echo $session['userid'];?>" ><?php echo $session['fname'];?></a></li>
		<li id="acountmenu" ><a href="http://www.freniz.com/index/personalinfo?log_aug=finis" >Account Settings</a></li>
		<li id="acountmenu"><a href="http://www.freniz.com/index/privacysettings" >Privacy Settings</a></li>
		<li class="active" id="acountmenu"><a href="http://www.freniz.com/index/advancedsettings" >Advanced Privacy</a></li>
	</ul>
</nav>
</div>
<div style="width:500px; margin-left:auto; margin-right:auto; padding:10px; ">
 
 <div id="scribble-rev" style="padding:10px; height:50px;">
 <label style="float:left; font-weight:bold; font-size:24px;">Scribbles Reviews:</label>
<div style="padding:5px; float:left; ">
<input checked="checked" type="radio" name="scribble" value="on"/>On
<input type="radio" name="scribble" value="off"/>Off
</div>
 </div>
 
 <div id="admire-rev" style="padding:10px; height:50px;">
 <label style="float:left; font-weight:bold; font-size:24px;">Admiration Reviews:</label>
<div style="padding:5px; float:left; ">
<input checked="checked" type="radio" name="admire" value="on"/>On
<input type="radio" name="admire" value="off"/>Off
</div>
 </div>
 
 <div id="image-rev" style="padding:10px; height:50px;">
 <label style="float:left; font-weight:bold; font-size:24px;">Photos Reviews:</label>
<div style="padding:5px; float:left; ">
<input checked="checked" type="radio" name="image" value="on"/>On
<input type="radio" name="image" value="off"/>Off
</div>
 </div>
 
 <div id="video-rev" style="padding:10px; height:50px;">
 <label style="float:left; font-weight:bold; font-size:24px;">videos Reviews:</label>
<div style="padding:5px; float:left; ">
<input checked="checked" type="radio" name="video" value="on"/>On
<input type="radio" name="video" value="off"/>Off
</div>
 </div>
 
 <div id="pin-rev" style="padding:10px; height:50px;">
 <label style="float:left; font-weight:bold; font-size:24px;">Pin Reviews:</label>
<div style="padding:5px; float:left; ">
<input checked="checked" type="radio" name="pin" value="on"/>On
<input type="radio" name="pin" value="off"/>Off
</div>
 </div>
 
 
 </div>
 

<div style="width:500px; margin-left:auto; margin-right:auto; padding:10px;  border-top:solid 1px">
<div id="basic-details" style="width:500px;  height:20px;">
<input onclick="basicaccount();" class="greenbutton" type="button" value="Update" />
<span id="basicload" class="show-load">loading...</span>

</div>

</div>
 
</div>


</div>





<div class="foot-tab" id="foot-tab">
    <ul>
 <li><a href="#">About</a></li>
         <li><a href="http://www.freniz.com/search">Search</a></li>
         <li><a href="#">Terms</a></li>
         <li><a href="#">Privacy</a></li>
         <li><a href="#">Help</a></li>
         <li><a href="http://www.freniz.com/createleaf">Create a leaf</a></li>
          <li><a href="http://www.freniz.com/developers">Developers</a></li>
         <li><a href="http://www.freniz.com/hireus">Hire Us</a></li>
     </ul>
     
 </div> 
 

</body>
</html>

