<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Login | Freniz</title>
<link rel="stylesheet" href="http://css.freniz.com/login.css" type="text/css" media="screen" charset="utf-8" />
<script type="text/javascript" src="http://js.freniz.com/jquery-latest.js"></script>
<script type="text/javascript" src="http://js.freniz.com/ajax.js"></script>
<script type="text/javascript" src="http://js.freniz.com/bsn.AutoSuggest_c_2.0.js"></script>
<link rel="stylesheet" href="http://css.freniz.com/autosuggest_inquisitor.css" type="text/css" media="screen" charset="utf-8" />

<style>
.curve {
    -moz-border-radius : 25px; /* Firefox */
    -webkit-border-radius :25px; /* Safari & Chrome */
    -khtml-border-radius : 25px; /* Linux browsers */
    border-radius : 25px; /* CSS3 compatible browsers */
}
body {
    margin: 0;
	width:99%;
    padding: 0;
    text-align: center; /* !!! */
}
.centered {
    margin: 0 auto;
    text-align: left;
    width: 1024px;
	
}
.greenbutton{

background-color: #C1DF79;
background-image: -webkit-gradient(linear, left top, left bottom, from(#C1DF79), to(#C1DF79));
background-image: -webkit-linear-gradient(top, #C1DF79, #C1DF79);
background-image: -moz-linear-gradient(top, #C1DF79, #C1DF79);
background-image: -ms-linear-gradient(top, #C1DF79, #C1DF79);
background-image: -o-linear-gradient(top, #C1DF79, #C1DF79);
background-image: linear-gradient(top, #C1DF79, #C1DF79);
-moz-border-radius: 3px;
-webkit-border-radius: 3px;
border-radius: 3px;
text-shadow: 0 1px 0 rgba(0, 0, 0, .5);
-moz-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;
-webkit-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;
box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;
border: 1px solid #7E1515;
float:right;
height: 20px;
padding: 0;
width: 50px;
cursor: pointer;
font: bold 12px Arial, Helvetica;
color: white;
}
.updatebutton{
background-color: #C1DF79;
background-image: -webkit-gradient(linear, left top, left bottom, from(#C1DF79), to(#C1DF79));
background-image: -webkit-linear-gradient(top, #C1DF79, #C1DF79);
background-image: -moz-linear-gradient(top, #C1DF79, #C1DF79);
background-image: -ms-linear-gradient(top, #C1DF79, #C1DF79);
background-image: -o-linear-gradient(top, #C1DF79, #C1DF79);
background-image: linear-gradient(top, #C1DF79, #C1DF79);
-moz-border-radius: 3px;
-webkit-border-radius: 3px;
border-radius: 3px;
text-shadow: 0 1px 0 rgba(0, 0, 0, .5);
-moz-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;
-webkit-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;
box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;
border: 1px solid #7E1515;
float:right;
height: 40px;
padding:10px;
width: 100px;
cursor: pointer;
font: bold 16px Arial, Helvetica;
color: white;
}
.foot-tab{
width:99%;

}
.foot-tab  ul{
                    display:block;
                    margin-top: -2px;
                    text-align:left;
                   margin-left: 10px;
                   
                }
               .foot-tab ul li{
                    display:inline-block; padding: 8px;
                    font-size: 12px;
                }
                .foot-tab ul li a{
                    text-decoration: none;
                    color: #000;
                    font-weight: bold;
                    cursor: pointer;
                }
                .foot-tab ul li a:hover{
                   text-decoration: underline;
                }
                .foot-tab{
                    border-top: solid 2px #ccc;
                    margin-top: 50px;
                  float: left;
                  margin-left: 2px;
                 
                }
                .foot-tab-pos{
                    position: absolute;
                }
                 .show-load{
                display:none;
                 position: absolute;
                  margin-left:550px;
                  
           width: 70px;
			height: 20px;
			background-color: #fff;
			z-index:1001;
			-moz-opacity: 0.8;
			opacity:.80;
			filter: alpha(opacity=80);
                }
               
</style>
<style>
	#side-menu ul{
		display:inline;
		width:150px;
		margin-top:-50px;
	}
	#side-menu ul li{
		display:block;
		background-color:#FFF;
		padding:20px;
		
		
	}
	#side-menu ul li a{
		text-decoration:none;
		color:black;
		position:absolute;
		padding:5px;
	}
	#side-menu ul li a:hover{
		background-color:#A4A4A4;
		width:150px;
		display:block;
		color:#FFF;
		 -moz-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  -webkit-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);	
		padding:5px;
		
		
	}
	.show-selected{
		background-color:#A4A4A4;
		width:150px;
		display:block;
		color:#FFF;
		 -moz-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  -webkit-box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		  box-shadow: 0 2px 2px -1px rgba(0,0,0,.9);
		padding:5px;
	}
	nav ul {
		  margin-top:0px;
		  padding: 2px;
		  list-style: none;
		  position: relative;
		  float: left;
		  background: #eee;
		  border-bottom: 1px solid #fff;
		  -moz-border-radius: 3px;
		  -webkit-border-radius: 3px;
		  border-radius: 3px;    
		}
		
		nav li {
		  float: left;      
			   border-left:solid 1px; 
		}
     
      nav li:first-child  a{
		   
			border-left:solid 1px #eee; 
		}
		
		nav #acountmenu a {
		  display: inline-block;
		  /*display: inline;
		  *zoom: 1;  */
		  height: 25px;
		  line-height: 25px;
		  font-weight: bold;
		  padding: 0 8px;
		  text-decoration: none;
		  color: #444;
		  text-shadow: 0 1px 0 #fff; 
		}
		
		nav #acountmenu a {
		  -moz-border-radius: 0 3px 3px 0;
		  -webkit-border-radius: 0 3px 3px 0;
		  border-radius: 0 3px 3px 0;
		}
		
		
			nav #acountmenu-trigger {
		  -moz-border-radius: 3px 0 0 3px;
		  -webkit-border-radius: 3px 0 0 3px;
		  border-radius: 3px 0 0 3px;
		}
		
		nav #acountmenu a:hover {
		  background: #fff;
		}
		.active{
		  background: #fff;
		}
	</style>
	</head>
</head>

<body>
 <div class="header-div-top" style="height:50px;">
             <a href="/"><div class="headername-font" style="width:220px; float:left; background-image: url(http://images.freniz.com/freniz.png); margin-top: -10px; height:60px; "></div></a>
     
</div>

<div style="margin-left:auto; margin-right:auto; width:1000px; height:400px;" >
<div style="width:280px; margin-top:10%; margin-left:10%; ">

<div style="width:75px; float:left; height:75px; border:solid 1px">
<img src="http://images.freniz.com/75/75_<?php echo $this->result['propic'];?>" />
</div>
<div style="width:200px; float:left; height:60px; ">
<label><?php echo $this->result['username'];?></label>
<input id="userid"  type="hidden" value="<?php echo $this->result['userid'];?>" />
<input id="password" onkeydown="login(event)" type="password" placeholder="Enter the password" style="width:200px; margin-left:5px;height:25px;" /> 
<input type="button" value="log in" onclick="login()" style="width:100px; margin-left:5px; margin-top:5px;height:20px;" /> 

</div>
</div>
</div>


  <div class="foot-tab" id="foot-tab">
    <ul>
 <li><a href="#">About</a></li>
         <li><a href="http://www.freniz.com/search">Search</a></li>
         <li><a href="#">Terms</a></li>
         <li><a href="#">Privacy</a></li>
         <li><a href="#">Help</a></li>
         <li><a href="http://www.freniz.com/createleaf">Create a leaf</a></li>
          <li><a href="http://www.freniz.com/developers">Developers</a></li>
         <li><a href="http://www.freniz.com/hireus">Hire Us</a></li>
     </ul>
     
 </div>
 <div id="light" class="white_content">
<img src="http://images.freniz.com/loading.gif"/>
</div>
<div id="fade" class="black_overlay">
        </div> 
</body>
</html>

