<?php $user_profile=$this->fbprofile; ?>
<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
           <script src="http://js.freniz.com/jquery-latest.js"></script>
         <script src="http://js.freniz.com/ajax.js"></script>
        
        <link rel="stylesheet" href="http://css.freniz.com/login.css" type="text/css" media="screen" charset="utf-8" />
  
        <style>
           
        </style>
    </head>
  <body>
  
   
     <div class="header-div-top" style="height:50px;">
       <a href="/"><div class="headername-font" style="width:220px; float:left; background-image: url(http://images.freniz.com/freniz.png); margin-top: -10px; height:60px; "></div></a>
        
          
               <ul>
		<li id="login">
                    <a id="signup-trigger" href="loginattempt" class="active">Login </a>
                </li>   </ul>
</div>
        
        
        
<div class="sign-outer">

    <div class="sign-main">

        <header>
            <h1 class="freniz-header">Sign up</h1>
            
        </header>

        
        
        

        <div class="login-details">
            

<form action="" method="post">
<table border="0" width="360" class="subfont" style="text-align:right" cellpadding="5">

<tr>
<td>User Name :</td>
<td><input type="text" size="30" height="20" name="username" id="username" value="<?php echo $user_profile['username'];?>" onkeyup="checkusername()" /></td>
</tr>
<tr>
<td>E-Mail ID :</td>
<td><input value="<?php echo $user_profile['email'];?>"  type="text" size="30" height="20" name="eid" id="eid" onkeyup="checkemail()" onfocus="checkmail()" /></td>
</tr>
<tr>
<td>Password :</td>
<td><input type="password" size="30" height="20" name="password1" id="password1" onkeyup="checkpassword()" /></td>
</tr>
<tr>
<td>Re-Password :</td>
 <td><input type="password" size="30" height="20" name="cpassword" id="cpassword" onkeyup="matchpassword()" /></td>
 </tr>

<input value="<?php echo $user_profile['first_name'];?>"  type="hidden" size="30" height="20" name="fname" id="fname" />

<input value="<?php echo $user_profile['last_name'];?>"  type="hidden" size="30" height="20" name="lname" id="lname"/>

<?php $sex=$user_profile['gender'];
if($sex=='female')
	$a=1;
else
	$a=2;
?>
<input value="<?php echo $a;?>"  type="hidden" size="30" height="20" name="sex" id="sex"/>
<?php $dat=$user_profile['birthday']; 
$dat=explode('/', $dat);

?>
<input value="<?php echo $dat['0'];?>"  type="hidden" size="30" height="20" id="birthday_month" name="birthday_month"/>
<input value="<?php echo $dat['1'];?>"  type="hidden" size="30" height="20" id="birthday_day" name="birthday_day"/>
<input value="<?php echo $dat['2'];?>"  type="hidden" size="30" height="20" id="birthday_year" name="birthday_year"/>
</table>

 <p class="form-actions">
      <label style="font-size:14px; margin-left: -10px; font-weight: bold ">By creating this account , I have understand and agree to the <a href="/">freniz Terms of Service</a>.</label>
     <br/>    <input onclick="createaccount()" class="reset-button" type="button" value="Sign up" />
      <div id="fb-root"></div>    
 
                </p>
</form>
        </div>

    </div>


    
<script>
    $(window).load(
        function() {
            $("#username").focus();
            checkusername();
            checkemail();
        }
    );
</script>

</div> <!-- .root -->
    <div id="light" class="white_content">
<img src="http://images.freniz.com/loading.gif"/>
</div>
<div id="fade" class="black_overlay">
        </div>
  </body>
</html>