<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Welcome to freniz - create or login into your world</title>
        <link rel="stylesheet" href="http://localhost/freniz_zend/public/css/welcome.css" type="text/css" media="screen" charset="utf-8" />
<script src="http://localhost/freniz_zend/public/js/jquery.js"></script>
    <script src="http://localhost/freniz_zend/public/js/ajax.js" type="text/javascript"></script>
    <link rel="shortcut icon" href="http://www.freniz.com/favicon.ico" />    

<style type="text/css">

body{
	background-color:#A9F5A9;
}
</style>
<style>
  .header-div-top div{
  	width:250px;
	position:absolute;
  	margin-top:-5px;
  	margin-left:70px;
  }
	.header-div-top  ul {
		  margin-top:0px;
		  padding: 2px;
		  list-style: none;
		  position: relative;
		  float: left;
		
		}
		
		.header-div-top li {
		  float: left;      
		}
     
      .header-div-top li:first-child  a{
		    color: #000;
		}
 .header-div-top li  a{
		    color: #fff;
		}
		
		.header-div-top #acountmenu a {
		  display: inline-block;
		  /*display: inline;
		  *zoom: 1;  */
		  height: 25px;
		  line-height: 25px;
		  font-weight: bold;
		  padding: 0px 8px;
		  text-decoration: none;
		  text-shadow: 0 1px 0 #fff; 
		}
		
		
		
		
		.active{
			
			 background: #fff;
		color:#000;
		}
		
	</style>
	
</head>
<body>
  <div class="header-div-top" style="height:40px;margin-top:10px;">
    <div style="float:left">
	<ul>
		<li class="active" id="acountmenu" ><a href="#" >Welcome</a></li>
		<li id="acountmenu"><a href="http://www.freniz.com/frenizsearch" >Search</a></li>
	</ul>
	</div>
       <div style="width:400px; height: 25px; position:absolute; right:0;">
            <input id="userid" onkeydown="login(event)" type="email" name="Email" placeholder="User Name" />
            <input id="password" onkeydown="login(event)" name="Password" type="password" placeholder="Password" /><br/>
           <span style=" padding:3px 10px; margin-top:-20px; float:left" onclick="login()" id="leaf-vote">Login</span>
              <div id="login-keep" style="float:left; margin-top:2px "><label><a href="http://www.freniz.com/resetpassword">forget password?</a></label><label style="font-size: 12px; font-weight: bold;margin-top: 3px; "><input style="float:left; margin-left:40px; " type="checkbox" checked="checked"/> Keep sign in</label></div>
           </div>  
         <img src="http://images.freniz.com/fb_connect_button.png" onclick="fblogin()"  style="float:right; cursor:pointer; margin-top:18px;" />
   
</div>
        
<div style="width:1000px; margin-left:auto; margin-right:auto; ">
<div style="width:200px;float:left; position:absolute; margin-top:20px; height:50px;  ">
    <a href="/"><div class="headername-font" style="width:220px; float:left; background-image: url(images/freniz-dark.png); margin-top: -15px; height:60px; "></div></a>
</div>
<div style="width:635px; background-image:url(http://images.freniz.com/frenizleaf.png);background-repeat:no-repeat; float:left; margin-top:70px; height:411px;  ">
</div>

<div style="width:340px; margin-top:-10px; color:#92D500;padding:10px;float:left;  ">

<div >

<!-- <input type="button" value="Connect With your FB"/></div>  <fb:login-button scope="email,user_birthday,publish_stream" >Connect With</fb:login-button> -->
<div id="fb-root"></div>
<label style="font-size:38px; font-weight:bold ; color:#3a3a3a">Create your world.</label>
<span  style="font-size:16px; margin-left:150px; font-weight:bold ;color:#3a3a3a;">It's no money...</span>
<form style="margin-top: -5px"action="" method="post">

<div style="width:340px; padding:5px">
<input type="text" style="width:340px; font-size:24px; height:40px " autocomplete="off" name="username"  placeholder="User Name" id="username" onkeyup="checkusername()" />
</div>
<div style="width:340px; padding:5px">
<input type="text" style="width:340px; font-size:24px; height:40px " autocomplete="off" name="eid" id="eid" onkeyup="checkemail()"  placeholder="Your email address" onkeyup="checkmail()" />
</div>
<div style="width:340px; padding:5px">
<input type="password"  style="width:340px; font-size:24px; height:40px " name="password1" id="password1"  placeholder="Your Password" onkeyup="checkpassword()" />
</div>
<div style="width:340px; padding:5px">
<input type="password"  style="width:340px; font-size:24px; height:40px " autocomplete="off" name="cpassword" id="cpassword"  placeholder="Again Password" onkeyup="matchpassword()" />
</div>
<div style="width:340px; padding:5px">
<input type="text"  style="width:160px; font-size:24px; height:40px "  placeholder="First Name" name="fname" id="fname" /><input type="text" style="width:160px; margin-left:5px;font-size:24px; height:40px " name="lname"  placeholder="Last Name" id="lname"/>
</div>
<div style="width:340px; padding:5px">
<span style="font-size:24px;  color:#3a3a3a;  font-weight:bold">Gender:</span>
<td style="text-align:left"><select  class="select" name="sex" id="sex"><option value="0">Select Sex:</option><option value="1">Female</option><option value="2">Male</option></select>
</td>
</div>
<div style="width:340px; padding:5px">
<span style="font-size:24px; color:#3a3a3a;  font-weight:bold">B'day:</span>
<select class="" id="birthday_month" name="birthday_month"><option value="-1">Month:</option><option value="1">Jan</option>
<option value="2">Feb</option>
<option value="3">Mar</option>
<option value="4">Apr</option>
<option value="5">May</option>
<option value="6">Jun</option>
<option value="7">Jul</option>
<option value="8">Aug</option>
<option value="9">Sep</option>
<option value="10">Oct</option>

<option value="11">Nov</option>
<option value="12">Dec</option>
</select> <select name="birthday_day" id="birthday_day"  onchange="bagofholding" autocomplete="off"><option value="-1">Day:</option><option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>

<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>

<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>

<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
</select> <select name="birthday_year" id="birthday_year"  autocomplete="off"><option value="-1">Year:</option><option value="2011">2011</option>

<option value="2010">2010</option>
<option value="2009">2009</option>
<option value="2008">2008</option>
<option value="2007">2007</option>
<option value="2006">2006</option>
<option value="2005">2005</option>
<option value="2004">2004</option>
<option value="2003">2003</option>
<option value="2002">2002</option>

<option value="2001">2001</option>
<option value="2000">2000</option>
<option value="1999">1999</option>
<option value="1998">1998</option>
<option value="1997">1997</option>
<option value="1996">1996</option>
<option value="1995">1995</option>
<option value="1994">1994</option>
<option value="1993">1993</option>

<option value="1992">1992</option>
<option value="1991">1991</option>
<option value="1990">1990</option>
<option value="1989">1989</option>
<option value="1988">1988</option>
<option value="1987">1987</option>
<option value="1986">1986</option>
<option value="1985">1985</option>
<option value="1984">1984</option>

<option value="1983">1983</option>
<option value="1982">1982</option>
<option value="1981">1981</option>
<option value="1980">1980</option>
<option value="1979">1979</option>
<option value="1978">1978</option>
<option value="1977">1977</option>
<option value="1976">1976</option>
<option value="1975">1975</option>

<option value="1974">1974</option>
<option value="1973">1973</option>
<option value="1972">1972</option>
<option value="1971">1971</option>
<option value="1970">1970</option>
<option value="1969">1969</option>
<option value="1968">1968</option>
<option value="1967">1967</option>
<option value="1966">1966</option>

<option value="1965">1965</option>
<option value="1964">1964</option>
<option value="1963">1963</option>
<option value="1962">1962</option>
<option value="1961">1961</option>
<option value="1960">1960</option>
<option value="1959">1959</option>
<option value="1958">1958</option>
<option value="1957">1957</option>

<option value="1956">1956</option>
<option value="1955">1955</option>
<option value="1954">1954</option>
<option value="1953">1953</option>
<option value="1952">1952</option>
<option value="1951">1951</option>
<option value="1950">1950</option>
<option value="1949">1949</option>
<option value="1948">1948</option>

<option value="1947">1947</option>
<option value="1946">1946</option>
<option value="1945">1945</option>
<option value="1944">1944</option>
<option value="1943">1943</option>
<option value="1942">1942</option>
<option value="1941">1941</option>
<option value="1940">1940</option>
<option value="1939">1939</option>

<option value="1938">1938</option>
<option value="1937">1937</option>
<option value="1936">1936</option>
<option value="1935">1935</option>
<option value="1934">1934</option>
<option value="1933">1933</option>
<option value="1932">1932</option>
<option value="1931">1931</option>
<option value="1930">1930</option>

<option value="1929">1929</option>
<option value="1928">1928</option>
<option value="1927">1927</option>
<option value="1926">1926</option>
<option value="1925">1925</option>
<option value="1924">1924</option>
<option value="1923">1923</option>
<option value="1922">1922</option>
<option value="1921">1921</option>

<option value="1920">1920</option>
<option value="1919">1919</option>
<option value="1918">1918</option>
<option value="1917">1917</option>
<option value="1916">1916</option>
<option value="1915">1915</option>
<option value="1914">1914</option>
<option value="1913">1913</option>
<option value="1912">1912</option>

<option value="1911">1911</option>
<option value="1910">1910</option>
<option value="1909">1909</option>
<option value="1908">1908</option>
<option value="1907">1907</option>
<option value="1906">1906</option>
<option value="1905">1905</option>
</select>
</div>
<div style=" width:340px;height:50px;font-size:16px;color:#3a3a3a; font-weight:bold;float:left">
<label><input type="checkbox" checked="checked">I have read, understand, and agree to the freniz Terms of Service.</label>
   <center style="margin-top:10px; "><span style=" padding:6px 40px; " onclick="createaccount()" id="leaf-vote">Create</span></center>
</div>
</form>


</div>




</div>
  <div class="foot-tab" id="foot-tab">
    <ul>
 <li><a href="#">About</a></li>
         <li><a href="http://www.freniz.com/search">Search</a></li>
         <li><a href="#">Terms</a></li>
         <li><a href="#">Privacy</a></li>
         <li><a href="#">Help</a></li>
         <li><a href="http://www.freniz.com/createleaf">Create a leaf</a></li>
          <li><a href="http://www.freniz.com/developers">Developers</a></li>
         <li><a href="http://www.freniz.com/hireus">Hire Us</a></li>
     </ul>
     
 </div> 
 
 <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37271806-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
 <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId: '<?php echo $this->FbAppId; ?>',
          cookie: true,
          xfbml: true,
          oauth: true
        });
        /*FB.getLoginStatus(function(response) {
      	  if (response.status === 'connected') {
      	    alert('connected');
      	  } else if (response.status === 'not_authorized') {
      	    alert('not_authorized');
      	  } else {
      	    alert('not login');
      	  }
      	 });*/
        
        
      };
      (function() {
        var e = document.createElement('script'); e.async = true;
        e.src = document.location.protocol +
          '//connect.facebook.net/en_US/all.js';
        document.getElementById('fb-root').appendChild(e);
      }());
      
      
      
      function fblogin(){
    	  FB.login(function(response){
    		  if (response.status === 'connected') {
  	      	    window.location.href="http://www.freniz.com/index/fbauth";
  	      	  } 

        	  },{scope:"email,user_birthday,publish_stream"});
      }
    </script>
<div id="light" class="white_content">
<img src="http://images.freniz.com/loading.gif"/>
</div>
<div id="fade" class="black_overlay">
        </div>
</body>


</html>