<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
          <script src="http://js.freniz.com/jquery-latest.js"></script>
        <link rel="stylesheet" href="http://css.freniz.com/login.css" type="text/css" media="screen" charset="utf-8" />
  <script src="http://js.freniz.com/ajax.js" type="text/javascript"></script>
 
        <style>
              
        </style>
    </head>
    <body>
       <div class="header-div-top" style="height:50px;">
       <a href="/"><div class="headername-font" style="width:220px; float:left; background-image: url(http://images.freniz.com/freniz.png); margin-top: -10px; height:60px; "></div></a>
           <ul>
		<li id="signup">
                    <a id="signup-trigger" href="signupaccount" class="active">Sign up </a>
                </li>   </ul>
</div>
        
         <?php if ($_REQUEST['error']=='1og_fail'){?>
        <div class="error-message">
        <h1>Error in Login !</h1>
        </div>
        <?php }?>
<div class="login-outer">

    <div class="login-main">

        <header>
            <h1 class="freniz-header">Login</h1>
            
        </header>

       
        

        <div class="login-details">
  
            <form method="POST" id="form-login" class="login">
              <p><label for="id_username">Username:</label> <input id="userid" onkeydown="login(event)"  type="text" name="username" maxlength="30"  /></p>
                 <p><label for="id_password">Password:</label> <input type="password" onkeydown="login(event)" name="password" id="password" /></p>
                <p class="form-actions">
                    <a href="resetpassword">Forgot password?</a>
                    <input type="button" onclick="login()" class="reset-button" value="Log in" />
                </p>
            </form>
        </div>

    </div>


<script>
    $(window).load(
        function() {
            $("#userid").focus();
        }
    );
</script>

</div> <!-- .root -->
<div id="light" class="white_content">
<img src="http://images.freniz.com/loading.gif"/>
</div>
<div id="fade" class="black_overlay">
        </div>
    </body>
</html>
