<html>
    <head>
        
        <link rel="stylesheet" href="css/login.css" type="text/css" media="screen" charset="utf-8" />
   <script src="js/jquery-latest.js"></script>
        <style>
            </style>
    </head>
    <body>
         <div class="header-div-top" style="height:50px;">
             <a href="/"><div class="headername-font" style="width:220px; float:left; background-image: url(http://images.freniz.com/freniz.png); margin-top: -10px; height:60px; "></div></a>
        <ul>
		<li id="signup">
                    <a id="signup-trigger" href="signupaccount" class="active">Sign up </a>
                </li>   </ul>  
             
               <ul>
		<li id="login">
                    <a id="signup-trigger" href="loginattempt" class="active">Login </a>
                </li>   </ul> 
</div>
        
        
        
        <div class="reset-main">
     
    <header>
        <h1>Reset Password</h1>
        <p>To reset your password, please enter the email that you used to register in freniz</p>
    </header>

    
<form  method="POST" accept-charset="utf-8" class="reset-password">

    <p class="text-form">
        <label>E-mail</label>
        <span><input id="email-id" type="text" name="email-name" maxlength="75" /></span>
    </p>
    
    
    

    <p class="reset-action"><input type="submit" class="reset-button" value="Reset Password" /></p>

</form>


    
<script>
    $(window).load(
        function() {
            $("#email-id").focus();
        }
    );
</script>

     </div> <!-- .main -->
    </body>
    
    
</html>