<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
           <script src="js/jquery-latest.js"></script>
        <link rel="stylesheet" href="css/login.css" type="text/css" media="screen" charset="utf-8" />
  <script src="js/ajax.js" type="text/javascript"></script>
 
        <style>
           
        </style>
    </head>
    <body>
       <div class="header-div-top" style="height:50px;">
       <a href="/"><div class="headername-font" style="width:220px; float:left; background-image: url(http://images.freniz.com/freniz.png); margin-top: -10px; height:60px; "></div></a>
        
          
               <ul>
		<li id="login">
                    <a id="signup-trigger" href="loginattempt" class="active">Login </a>
                </li>   </ul>
</div>
        
        
        
<div class="sign-outer">

    <div class="sign-main">

        <header>
            <h1 class="freniz-header">Sign up</h1>
            
        </header>

        
        
        

        <div class="login-details">
            

<form action="" method="post">
<table border="0" width="360" class="subfont" style="text-align:right" cellpadding="5">
<tr>
<td>User Name :</td>
<td><input type="text" size="30" height="20" autocomplete="off" name="username" id="username" onkeyup="checkusername()" /></td>
</tr>
<tr>
<td>E-Mail ID :</td>
<td><input type="text" size="30" height="20" autocomplete="off"  name="eid" id="eid" onkeyup="checkemail()" onfocus="checkmail()" /></td>
</tr>
<tr>
<td>Password :</td>
<td><input type="password" size="30" height="20" autocomplete="off"  name="password1" id="password1" onkeyup="checkpassword()" /></td>
</tr>
<tr>
<td>Re-Password :</td>
 <td><input type="password" size="30" height="20" autocomplete="off"  name="cpassword" id="cpassword" onkeyup="matchpassword()" /></td>
 </tr>
<tr>
<td>First Name :</td>
<td><input type="text" size="30" height="20" autocomplete="off"  name="fname" id="fname" /></td>
</tr>
<tr></tr>
<tr>
<td>Last Name :</td>
<td><input type="text" size="30" height="20" autocomplete="off"  name="lname" id="lname"/></td>
</tr>

<tr>
<td>Sex :</td>
<td style="text-align:left"><select class="select" name="sex" id="sex"><option value="0">Select Sex:</option><option value="1">Female</option><option value="2">Male</option></select>
</td>
</tr>
<tr>
<td>Birth Day :</td>
<td style="text-align:left"><select class="" id="birthday_month" name="birthday_month"><option value="-1">Month:</option><option value="1">Jan</option>
<option value="2">Feb</option>
<option value="3">Mar</option>
<option value="4">Apr</option>
<option value="5">May</option>
<option value="6">Jun</option>
<option value="7">Jul</option>
<option value="8">Aug</option>
<option value="9">Sep</option>
<option value="10">Oct</option>

<option value="11">Nov</option>
<option value="12">Dec</option>
</select> <select name="birthday_day" id="birthday_day"  onchange="bagofholding" autocomplete="off"><option value="-1">Day:</option><option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>

<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>

<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>

<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
</select> <select name="birthday_year" id="birthday_year"  autocomplete="off"><option value="-1">Year:</option><option value="2011">2011</option>

<option value="2010">2010</option>
<option value="2009">2009</option>
<option value="2008">2008</option>
<option value="2007">2007</option>
<option value="2006">2006</option>
<option value="2005">2005</option>
<option value="2004">2004</option>
<option value="2003">2003</option>
<option value="2002">2002</option>

<option value="2001">2001</option>
<option value="2000">2000</option>
<option value="1999">1999</option>
<option value="1998">1998</option>
<option value="1997">1997</option>
<option value="1996">1996</option>
<option value="1995">1995</option>
<option value="1994">1994</option>
<option value="1993">1993</option>

<option value="1992">1992</option>
<option value="1991">1991</option>
<option value="1990">1990</option>
<option value="1989">1989</option>
<option value="1988">1988</option>
<option value="1987">1987</option>
<option value="1986">1986</option>
<option value="1985">1985</option>
<option value="1984">1984</option>

<option value="1983">1983</option>
<option value="1982">1982</option>
<option value="1981">1981</option>
<option value="1980">1980</option>
<option value="1979">1979</option>
<option value="1978">1978</option>
<option value="1977">1977</option>
<option value="1976">1976</option>
<option value="1975">1975</option>

<option value="1974">1974</option>
<option value="1973">1973</option>
<option value="1972">1972</option>
<option value="1971">1971</option>
<option value="1970">1970</option>
<option value="1969">1969</option>
<option value="1968">1968</option>
<option value="1967">1967</option>
<option value="1966">1966</option>

<option value="1965">1965</option>
<option value="1964">1964</option>
<option value="1963">1963</option>
<option value="1962">1962</option>
<option value="1961">1961</option>
<option value="1960">1960</option>
<option value="1959">1959</option>
<option value="1958">1958</option>
<option value="1957">1957</option>

<option value="1956">1956</option>
<option value="1955">1955</option>
<option value="1954">1954</option>
<option value="1953">1953</option>
<option value="1952">1952</option>
<option value="1951">1951</option>
<option value="1950">1950</option>
<option value="1949">1949</option>
<option value="1948">1948</option>

<option value="1947">1947</option>
<option value="1946">1946</option>
<option value="1945">1945</option>
<option value="1944">1944</option>
<option value="1943">1943</option>
<option value="1942">1942</option>
<option value="1941">1941</option>
<option value="1940">1940</option>
<option value="1939">1939</option>

<option value="1938">1938</option>
<option value="1937">1937</option>
<option value="1936">1936</option>
<option value="1935">1935</option>
<option value="1934">1934</option>
<option value="1933">1933</option>
<option value="1932">1932</option>
<option value="1931">1931</option>
<option value="1930">1930</option>

<option value="1929">1929</option>
<option value="1928">1928</option>
<option value="1927">1927</option>
<option value="1926">1926</option>
<option value="1925">1925</option>
<option value="1924">1924</option>
<option value="1923">1923</option>
<option value="1922">1922</option>
<option value="1921">1921</option>

<option value="1920">1920</option>
<option value="1919">1919</option>
<option value="1918">1918</option>
<option value="1917">1917</option>
<option value="1916">1916</option>
<option value="1915">1915</option>
<option value="1914">1914</option>
<option value="1913">1913</option>
<option value="1912">1912</option>

<option value="1911">1911</option>
<option value="1910">1910</option>
<option value="1909">1909</option>
<option value="1908">1908</option>
<option value="1907">1907</option>
<option value="1906">1906</option>
<option value="1905">1905</option>
</select></td>
</tr>
</table>

 <p class="form-actions">
     <input type="checkbox">
     <label style="font-size:14px; margin-left: -70px; font-weight: bold ">I have understand and agree to the <a href="/">freniz Terms of Service</a>.</label>
     <br/>       <input type="submit" onclick="createaccount()" class="reset-button" value="Sign up" />
 
                </p>
</form>
        </div>

    </div>


    
<script>
    $(window).load(
        function() {
            $("#username").focus();
        }
    );
</script>

</div> <!-- .root -->

    </body>
</html>
